<?php
// This is file installs the map data for the DarkAges variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Agder', 'Coast', 'No', 4, 852, 333, 498, 181),
	array('Alvheim', 'Coast', 'Yes', 0, 1032, 363, 581, 205),
	array('Arctic Ocean', 'Sea', 'No', 0, 290, 163, 133, 100),
	array('Arhus', 'Coast', 'No', 6, 953, 467, 538, 264),
	array('Atlantic Ocean', 'Sea', 'No', 0, 147, 692, 84, 392),
	array('Austrasia', 'Coast', 'Yes', 0, 662, 813, 361, 456),
	array('Baltic Sea', 'Sea', 'No', 0, 1245, 509, 698, 268),
	array('Bay of Biscay', 'Sea', 'No', 0, 177, 907, 103, 503),
	array('Gulf of Bothnia', 'Sea', 'No', 0, 1304, 245, 728, 143),
	array('Bay of Reric', 'Sea', 'No', 0, 1024, 585, 547, 353),
	array('Bernicia', 'Coast', 'No', 2, 508, 450, 284, 252),
	array('Bristol Channel', 'Sea', 'No', 0, 293, 697, 154, 393),
	array('Cait', 'Coast', 'Yes', 2, 478, 240, 272, 141),
	array('Cardigan Bay', 'Sea', 'No', 0, 282, 613, 183, 316),
	array('Chester', 'Coast', 'No', 3, 455, 520, 257, 298),
	array('Circinn', 'Coast', 'Yes', 2, 525, 335, 293, 191),
	array('Connaught', 'Coast', 'No', 1, 188, 422, 106, 265),
	array('Cornwall', 'Coast', 'Yes', 0, 260, 735, 156, 405),
	array('Dal Riada', 'Coast', 'Yes', 0, 417, 370, 237, 220),
	array('Deira', 'Coast', 'Yes', 0, 533, 538, 293, 291),
	array('Douglas Bay', 'Sea', 'No', 0, 414, 523, 237, 294),
	array('Dyfed', 'Coast', 'Yes', 3, 315, 633, 193, 367),
	array('East Anglia', 'Coast', 'Yes', 5, 577, 650, 324, 360),
	array('English Channel', 'Sea', 'No', 0, 362, 815, 252, 449),
	array('Firth of Forth', 'Sea', 'No', 0, 542, 437, 306, 243),
	array('Fortrenn', 'Coast', 'Yes', 2, 497, 305, 279, 171),
	array('Frisia', 'Coast', 'Yes', 0, 770, 677, 403, 382),
	array('Gotar', 'Coast', 'Yes', 7, 1153, 410, 647, 229),
	array('Gwent', 'Coast', 'No', 3, 378, 675, 212, 377),
	array('Gwynned', 'Coast', 'Yes', 3, 386, 590, 203, 322),
	array('Hamptonshire', 'Coast', 'Yes', 5, 422, 736, 232, 422),
	array('Hebridean Sea', 'Sea', 'No', 0, 310, 310, 193, 169),
	array('Hordaland', 'Coast', 'Yes', 4, 834, 207, 470, 105),
	array('Hwicce', 'Coast', 'No', 3, 443, 650, 239, 385),
	array('Isle of Man', 'Coast', 'Yes', 0, 383, 501, 215, 271),
	array('Jamtland', 'Land', 'No', 7, 1088, 118, 609, 43),
	array('Jelling', 'Coast', 'Yes', 6, 907, 513, 507, 290),
	array('Kattegat', 'Sea', 'No', 0, 1006, 476, 567, 272),
	array('Kent', 'Coast', 'Yes', 5, 555, 707, 316, 396),
	array('Lancaster', 'Coast', 'Yes', 0, 457, 488, 257, 259),
	array('Lappland', 'Coast', 'Yes', 7, 1183, 62, 661, 34),
	array('Leinster', 'Coast', 'Yes', 1, 255, 577, 138, 326),
	array('Lindholm', 'Coast', 'Yes', 0, 965, 415, 540, 235),
	array('Lindsey', 'Coast', 'No', 5, 537, 577, 301, 321),
	array('Manx Sea', 'Sea', 'No', 0, 350, 520, 201, 293),
	array('Masovia', 'Land', 'No', 0, 1209, 815, 680, 469),
	array('Meath', 'Coast', 'Yes', 1, 300, 485, 169, 273),
	array('Mercia', 'Land', 'Yes', 0, 492, 630, 270, 359),
	array('Middle Anglia', 'Coast', 'No', 5, 522, 650, 291, 365),
	array('Moray Firth', 'Sea', 'No', 0, 597, 303, 333, 171),
	array('Munster', 'Coast', 'No', 1, 145, 578, 84, 319),
	array('Neustria', 'Coast', 'No', 0, 318, 892, 238, 494),
	array('North Atlantic Ocean', 'Sea', 'No', 0, 65, 435, 60, 234),
	array('North Channel', 'Sea', 'No', 0, 377, 375, 207, 238),
	array('North Frisian Coast', 'Sea', 'No', 0, 813, 542, 460, 325),
	array('North Sea', 'Sea', 'No', 0, 698, 483, 386, 265),
	array('Norwegian Sea', 'Sea', 'No', 0, 735, 108, 414, 51),
	array('Opplandene', 'Land', 'No', 4, 985, 187, 565, 82),
	array('Pengwern', 'Coast', 'No', 3, 382, 547, 214, 309),
	array('Powys', 'Land', 'Yes', 3, 413, 612, 235, 337),
	array('Ramsey Bay', 'Sea', 'No', 0, 417, 473, 236, 268),
	array('Reric', 'Coast', 'Yes', 0, 1043, 655, 634, 379),
	array('Ribe', 'Coast', 'Yes', 6, 917, 612, 513, 342),
	array('Rogaland', 'Coast', 'Yes', 4, 842, 260, 471, 146),
	array('Rogaland Coast', 'Sea', 'No', 0, 752, 275, 416, 158),
	array('Roskilde', 'Coast', 'Yes', 6, 997, 553, 559, 293),
	array('Saxony', 'Coast', 'No', 6, 910, 662, 510, 377),
	array('Scapa Flow', 'Sea', 'No', 0, 527, 187, 287, 114),
	array('Skagerrak', 'Sea', 'No', 0, 972, 372, 533, 209),
	array('Skane', 'Coast', 'Yes', 0, 1125, 500, 618, 283),
	array('Sogn', 'Coast', 'No', 4, 858, 118, 484, 67),
	array('Somerset', 'Coast', 'No', 5, 370, 721, 216, 398),
	array('Strait of Dover', 'Sea', 'No', 0, 617, 707, 323, 414),
	array('Strathclyde', 'Coast', 'No', 0, 417, 417, 237, 236),
	array('Surrey', 'Land', 'No', 5, 488, 722, 270, 405),
	array('Sussex', 'Coast', 'No', 5, 532, 757, 285, 415),
	array('Svear', 'Coast', 'Yes', 7, 1214, 262, 678, 150),
	array('Ulster', 'Coast', 'Yes', 1, 330, 430, 183, 242),
	array('The Wash', 'Sea', 'No', 0, 588, 600, 317, 290),
	array('Thuringia', 'Land', 'No', 0, 1005, 905, 566, 484),
	array('Trondheim', 'Coast', 'Yes', 0, 930, 63, 523, 35),
	array('Varmland', 'Land', 'Yes', 0, 1066, 246, 609, 112),
	array('Viborg', 'Coast', 'No', 6, 903, 482, 502, 263),
	array('Vineta', 'Coast', 'Yes', 0, 1309, 636, 734, 359),
	array('Vestfold', 'Coast', 'Yes', 4, 968, 306, 545, 173),
	array('West Frisian Coast', 'Sea', 'No', 0, 700, 644, 357, 363),
	array('Zetland', 'Coast', 'Yes', 0, 620, 205, 347, 115),
	array('Jelling (East Coast)', 'Coast', 'No', 6, 915, 526, 514, 291),
	array('Jelling (West Coast)', 'Coast', 'No', 6, 886, 547, 491, 306),
	array('Lappland (East Coast)', 'Coast', 'No', 7, 1244, 78, 680, 63),
	array('Lappland (West Coast)', 'Coast', 'No', 7, 1028, 25, 568, 11),
	array('Somerset (North Coast)', 'Coast', 'No', 0, 371, 708, 212, 395),
	array('Somerset (South Coast)', 'Coast', 'No', 0, 357, 731, 200, 409),
	array('gaels', 'Land', 'No', 1, 0, 0, 72, 43),
	array('scots', 'Coast', 'No', 2, 0, 0, 71, 56),
	array('bretons', 'Coast', 'No', 3, 0, 0, 72, 67),
	array('anglosaxons', 'Coast', 'No', 5, 0, 0, 72, 80),
	array('danes', 'Coast', 'No', 6, 0, 0, 72, 91),
	array('norse', 'Coast', 'No', 4, 0, 0, 72, 103),
	array('swedes', 'Coast', 'No', 7, 0, 0, 72, 115)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Agder','Rogaland','Yes','Yes'),
	array('Agder','Skagerrak','Yes','No'),
	array('Agder','Vestfold','Yes','Yes'),
	array('Alvheim','Gotar','No','Yes'),
	array('Alvheim','Skagerrak','Yes','No'),
	array('Alvheim','Skane','Yes','Yes'),
	array('Alvheim','Varmland','No','Yes'),
	array('Alvheim','Vestfold','Yes','Yes'),
	array('Arctic Ocean','Hebridean Sea','Yes','No'),
	array('Arctic Ocean','North Atlantic Ocean','Yes','No'),
	array('Arctic Ocean','Norwegian Sea','Yes','No'),
	array('Arctic Ocean','Scapa Flow','Yes','No'),
	array('Arhus','Jelling','No','Yes'),
	array('Arhus','Kattegat','Yes','No'),
	array('Arhus','Lindholm','Yes','Yes'),
	array('Arhus','Viborg','No','Yes'),
	array('Arhus','Jelling (East Coast)','Yes','No'),
	array('Atlantic Ocean','Bay of Biscay','Yes','No'),
	array('Atlantic Ocean','Bristol Channel','Yes','No'),
	array('Atlantic Ocean','Cardigan Bay','Yes','No'),
	array('Atlantic Ocean','Cornwall','Yes','No'),
	array('Atlantic Ocean','English Channel','Yes','No'),
	array('Atlantic Ocean','Leinster','Yes','No'),
	array('Atlantic Ocean','Munster','Yes','No'),
	array('Atlantic Ocean','Neustria','Yes','No'),
	array('Atlantic Ocean','North Atlantic Ocean','Yes','No'),
	array('Austrasia','English Channel','Yes','No'),
	array('Austrasia','Frisia','Yes','Yes'),
	array('Austrasia','Neustria','Yes','Yes'),
	array('Austrasia','Saxony','No','Yes'),
	array('Austrasia','Strait of Dover','Yes','No'),
	array('Austrasia','Thuringia','No','Yes'),
	array('Baltic Sea','Gulf of Bothnia','Yes','No'),
	array('Baltic Sea','Bay of Reric','Yes','No'),
	array('Baltic Sea','Gotar','Yes','No'),
	array('Baltic Sea','Reric','Yes','No'),
	array('Baltic Sea','Skane','Yes','No'),
	array('Baltic Sea','Svear','Yes','No'),
	array('Baltic Sea','Vineta','Yes','No'),
	array('Bay of Biscay','Neustria','Yes','No'),
	array('Gulf of Bothnia','Svear','Yes','No'),
	array('Gulf of Bothnia','Lappland (East Coast)','Yes','No'),
	array('Bay of Reric','Kattegat','Yes','No'),
	array('Bay of Reric','Reric','Yes','No'),
	array('Bay of Reric','Ribe','Yes','No'),
	array('Bay of Reric','Roskilde','Yes','No'),
	array('Bay of Reric','Saxony','Yes','No'),
	array('Bay of Reric','Skane','Yes','No'),
	array('Bay of Reric','Jelling (East Coast)','Yes','No'),
	array('Bernicia','Circinn','Yes','Yes'),
	array('Bernicia','Dal Riada','No','Yes'),
	array('Bernicia','Deira','Yes','Yes'),
	array('Bernicia','Firth of Forth','Yes','No'),
	array('Bernicia','Lancaster','No','Yes'),
	array('Bernicia','Strathclyde','No','Yes'),
	array('Bernicia','The Wash','Yes','No'),
	array('Bristol Channel','Cardigan Bay','Yes','No'),
	array('Bristol Channel','Cornwall','Yes','No'),
	array('Bristol Channel','Dyfed','Yes','No'),
	array('Bristol Channel','Gwent','Yes','No'),
	array('Bristol Channel','Hwicce','Yes','No'),
	array('Bristol Channel','Somerset (North Coast)','Yes','No'),
	array('Cait','Dal Riada','Yes','Yes'),
	array('Cait','Fortrenn','Yes','Yes'),
	array('Cait','Hebridean Sea','Yes','No'),
	array('Cait','Moray Firth','Yes','No'),
	array('Cait','Scapa Flow','Yes','No'),
	array('Cardigan Bay','Dyfed','Yes','No'),
	array('Cardigan Bay','Gwynned','Yes','No'),
	array('Cardigan Bay','Leinster','Yes','No'),
	array('Cardigan Bay','Manx Sea','Yes','No'),
	array('Cardigan Bay','Pengwern','Yes','No'),
	array('Chester','Deira','No','Yes'),
	array('Chester','Douglas Bay','Yes','No'),
	array('Chester','Lancaster','Yes','Yes'),
	array('Chester','Mercia','No','Yes'),
	array('Chester','Pengwern','Yes','Yes'),
	array('Chester','Powys','No','Yes'),
	array('Circinn','Dal Riada','No','Yes'),
	array('Circinn','Firth of Forth','Yes','No'),
	array('Circinn','Fortrenn','Yes','Yes'),
	array('Circinn','Moray Firth','Yes','No'),
	array('Connaught','Hebridean Sea','Yes','No'),
	array('Connaught','Meath','No','Yes'),
	array('Connaught','Munster','Yes','Yes'),
	array('Connaught','North Atlantic Ocean','Yes','No'),
	array('Connaught','Ulster','Yes','Yes'),
	array('Cornwall','English Channel','Yes','No'),
	array('Cornwall','Somerset','No','Yes'),
	array('Cornwall','Somerset (North Coast)','Yes','No'),
	array('Cornwall','Somerset (South Coast)','Yes','No'),
	array('Dal Riada','Fortrenn','No','Yes'),
	array('Dal Riada','Hebridean Sea','Yes','No'),
	array('Dal Riada','North Channel','Yes','No'),
	array('Dal Riada','Strathclyde','Yes','Yes'),
	array('Deira','Lancaster','No','Yes'),
	array('Deira','Lindsey','Yes','Yes'),
	array('Deira','Mercia','No','Yes'),
	array('Deira','The Wash','Yes','No'),
	array('Douglas Bay','Douglas Bay','Yes','No'),
	array('Douglas Bay','Isle of Man','Yes','No'),
	array('Douglas Bay','Lancaster','Yes','No'),
	array('Douglas Bay','Manx Sea','Yes','No'),
	array('Douglas Bay','Pengwern','Yes','No'),
	array('Douglas Bay','Ramsey Bay','Yes','No'),
	array('Dyfed','Gwent','Yes','Yes'),
	array('Dyfed','Gwynned','Yes','Yes'),
	array('Dyfed','Powys','No','Yes'),
	array('East Anglia','Kent','Yes','Yes'),
	array('East Anglia','Middle Anglia','Yes','Yes'),
	array('East Anglia','Strait of Dover','Yes','No'),
	array('East Anglia','The Wash','Yes','No'),
	array('East Anglia','West Frisian Coast','Yes','No'),
	array('English Channel','Hamptonshire','Yes','No'),
	array('English Channel','Neustria','Yes','No'),
	array('English Channel','Strait of Dover','Yes','No'),
	array('English Channel','Sussex','Yes','No'),
	array('English Channel','Somerset (South Coast)','Yes','No'),
	array('Firth of Forth','Moray Firth','Yes','No'),
	array('Firth of Forth','North Sea','Yes','No'),
	array('Firth of Forth','The Wash','Yes','No'),
	array('Fortrenn','Moray Firth','Yes','No'),
	array('Frisia','North Frisian Coast','Yes','No'),
	array('Frisia','Saxony','Yes','Yes'),
	array('Frisia','Strait of Dover','Yes','No'),
	array('Frisia','West Frisian Coast','Yes','No'),
	array('Gotar','Skane','Yes','Yes'),
	array('Gotar','Svear','Yes','Yes'),
	array('Gotar','Varmland','No','Yes'),
	array('Gwent','Hwicce','Yes','Yes'),
	array('Gwent','Powys','No','Yes'),
	array('Gwynned','Pengwern','Yes','Yes'),
	array('Gwynned','Powys','No','Yes'),
	array('Hamptonshire','Hwicce','No','Yes'),
	array('Hamptonshire','Somerset','No','Yes'),
	array('Hamptonshire','Surrey','No','Yes'),
	array('Hamptonshire','Sussex','Yes','Yes'),
	array('Hamptonshire','Somerset (South Coast)','Yes','No'),
	array('Hebridean Sea','North Atlantic Ocean','Yes','No'),
	array('Hebridean Sea','North Channel','Yes','No'),
	array('Hebridean Sea','Scapa Flow','Yes','No'),
	array('Hebridean Sea','Ulster','Yes','No'),
	array('Hordaland','Norwegian Sea','Yes','No'),
	array('Hordaland','Opplandene','No','Yes'),
	array('Hordaland','Rogaland','Yes','Yes'),
	array('Hordaland','Rogaland Coast','Yes','No'),
	array('Hordaland','Sogn','Yes','Yes'),
	array('Hordaland','Vestfold','No','Yes'),
	array('Hwicce','Mercia','No','Yes'),
	array('Hwicce','Middle Anglia','No','Yes'),
	array('Hwicce','Powys','No','Yes'),
	array('Hwicce','Somerset','No','Yes'),
	array('Hwicce','Surrey','No','Yes'),
	array('Hwicce','Somerset (North Coast)','Yes','No'),
	array('Isle of Man','Lancaster','Yes','Yes'),
	array('Isle of Man','Manx Sea','Yes','No'),
	array('Isle of Man','North Channel','Yes','No'),
	array('Isle of Man','Pengwern','Yes','Yes'),
	array('Isle of Man','Ramsey Bay','Yes','No'),
	array('Isle of Man','Strathclyde','Yes','Yes'),
	array('Isle of Man','Ulster','Yes','Yes'),
	array('Jamtland','Lappland','No','Yes'),
	array('Jamtland','Opplandene','No','Yes'),
	array('Jamtland','Svear','No','Yes'),
	array('Jamtland','Trondheim','No','Yes'),
	array('Jamtland','Varmland','No','Yes'),
	array('Jelling','Ribe','No','Yes'),
	array('Jelling','Roskilde','No','Yes'),
	array('Jelling','Viborg','No','Yes'),
	array('Kattegat','Lindholm','Yes','No'),
	array('Kattegat','Roskilde','Yes','No'),
	array('Kattegat','Skagerrak','Yes','No'),
	array('Kattegat','Skane','Yes','No'),
	array('Kattegat','Jelling (East Coast)','Yes','No'),
	array('Kent','Middle Anglia','No','Yes'),
	array('Kent','Strait of Dover','Yes','No'),
	array('Kent','Surrey','No','Yes'),
	array('Kent','Sussex','Yes','Yes'),
	array('Lancaster','Ramsey Bay','Yes','No'),
	array('Lancaster','Strathclyde','Yes','Yes'),
	array('Lappland','Svear','No','Yes'),
	array('Lappland','Trondheim','No','Yes'),
	array('Leinster','Manx Sea','Yes','No'),
	array('Leinster','Meath','Yes','Yes'),
	array('Leinster','Munster','Yes','Yes'),
	array('Lindholm','Skagerrak','Yes','No'),
	array('Lindholm','Viborg','Yes','Yes'),
	array('Lindsey','Mercia','No','Yes'),
	array('Lindsey','Middle Anglia','Yes','Yes'),
	array('Lindsey','The Wash','Yes','No'),
	array('Manx Sea','Meath','Yes','No'),
	array('Manx Sea','North Channel','Yes','No'),
	array('Manx Sea','Pengwern','Yes','No'),
	array('Manx Sea','Ulster','Yes','No'),
	array('Masovia','Reric','No','Yes'),
	array('Masovia','Thuringia','No','Yes'),
	array('Masovia','Vineta','No','Yes'),
	array('Meath','Munster','No','Yes'),
	array('Meath','Ulster','Yes','Yes'),
	array('Mercia','Middle Anglia','No','Yes'),
	array('Mercia','Powys','No','Yes'),
	array('Middle Anglia','Surrey','No','Yes'),
	array('Middle Anglia','The Wash','Yes','No'),
	array('Moray Firth','North Sea','Yes','No'),
	array('Moray Firth','Rogaland Coast','Yes','No'),
	array('Moray Firth','Scapa Flow','Yes','No'),
	array('Moray Firth','Zetland','Yes','No'),
	array('Munster','North Atlantic Ocean','Yes','No'),
	array('North Channel','Ramsey Bay','Yes','No'),
	array('North Channel','Strathclyde','Yes','No'),
	array('North Channel','Ulster','Yes','No'),
	array('North Frisian Coast','North Sea','Yes','No'),
	array('North Frisian Coast','Ribe','Yes','No'),
	array('North Frisian Coast','Saxony','Yes','No'),
	array('North Frisian Coast','Skagerrak','Yes','No'),
	array('North Frisian Coast','Viborg','Yes','No'),
	array('North Frisian Coast','West Frisian Coast','Yes','No'),
	array('North Frisian Coast','Jelling (West Coast)','Yes','No'),
	array('North Sea','Rogaland Coast','Yes','No'),
	array('North Sea','Skagerrak','Yes','No'),
	array('North Sea','The Wash','Yes','No'),
	array('North Sea','West Frisian Coast','Yes','No'),
	array('Norwegian Sea','Rogaland Coast','Yes','No'),
	array('Norwegian Sea','Scapa Flow','Yes','No'),
	array('Norwegian Sea','Sogn','Yes','No'),
	array('Norwegian Sea','Trondheim','Yes','No'),
	array('Norwegian Sea','Zetland','Yes','No'),
	array('Norwegian Sea','Lappland (West Coast)','Yes','No'),
	array('Opplandene','Sogn','No','Yes'),
	array('Opplandene','Trondheim','No','Yes'),
	array('Opplandene','Varmland','No','Yes'),
	array('Opplandene','Vestfold','No','Yes'),
	array('Pengwern','Powys','No','Yes'),
	array('Ramsey Bay','Strathclyde','Yes','No'),
	array('Reric','Saxony','Yes','Yes'),
	array('Reric','Thuringia','No','Yes'),
	array('Reric','Vineta','Yes','Yes'),
	array('Ribe','Saxony','Yes','Yes'),
	array('Ribe','Jelling (East Coast)','Yes','No'),
	array('Ribe','Jelling (West Coast)','Yes','No'),
	array('Rogaland','Rogaland Coast','Yes','No'),
	array('Rogaland','Skagerrak','Yes','No'),
	array('Rogaland','Vestfold','No','Yes'),
	array('Rogaland Coast','Skagerrak','Yes','No'),
	array('Rogaland Coast','Zetland','Yes','No'),
	array('Roskilde','Skane','Yes','Yes'),
	array('Roskilde','Jelling (East Coast)','Yes','No'),
	array('Saxony','Thuringia','No','Yes'),
	array('Scapa Flow','Zetland','Yes','No'),
	array('Skagerrak','Skane','Yes','No'),
	array('Skagerrak','Viborg','Yes','No'),
	array('Skagerrak','Vestfold','Yes','No'),
	array('Sogn','Trondheim','Yes','Yes'),
	array('Strait of Dover','Sussex','Yes','No'),
	array('Strait of Dover','West Frisian Coast','Yes','No'),
	array('Surrey','Sussex','No','Yes'),
	array('Svear','Varmland','No','Yes'),
	array('Svear','Lappland (East Coast)','Yes','No'),
	array('The Wash','West Frisian Coast','Yes','No'),
	array('Trondheim','Lappland (West Coast)','Yes','No'),
	array('Varmland','Vestfold','No','Yes'),
	array('Viborg','Jelling (West Coast)','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
