<?php
// This is file installs the map data for the ClassicLayered variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Adriatic Sea 1', 'Sea', 'No', 0, 554, 761, 316, 329),
	array('Adriatic Sea 2', 'Sea', 'No', 0, 1857, 757, 317, 730),
	array('Aegean Sea 1', 'Sea', 'No', 0, 755, 930, 395, 363),
	array('Aegean Sea 2', 'Sea', 'No', 0, 2070, 917, 395, 763),
	array('Albania 1', 'Coast', 'No', 0, 640, 820, 343, 341),
	array('Albania 2', 'Coast', 'No', 0, 1947, 815, 343, 741),
	array('Ankara 1', 'Coast', 'Yes', 6, 970, 820, 485, 320),
	array('Ankara 2', 'Coast', 'Yes', 6, 2282, 810, 485, 720),
	array('Apulia 1', 'Coast', 'No', 3, 574, 813, 295, 335),
	array('Apulia 2', 'Coast', 'No', 3, 1871, 810, 295, 735),
	array('Armenia 1', 'Coast', 'No', 6, 1130, 835, 572, 323),
	array('Armenia 2', 'Coast', 'No', 6, 2434, 826, 572, 723),
	array('Baltic Sea 1', 'Sea', 'No', 0, 621, 431, 338, 177),
	array('Baltic Sea 2', 'Sea', 'No', 0, 1939, 425, 342, 568),
	array('Barents Sea 1', 'Sea', 'No', 0, 826, 37, 427, 15),
	array('Barents Sea 2', 'Sea', 'No', 0, 2137, 29, 427, 415),
	array('Belgium 1', 'Coast', 'Yes', 0, 410, 550, 215, 205),
	array('Belgium 2', 'Coast', 'Yes', 0, 1717, 551, 215, 605),
	array('Berlin 1', 'Coast', 'Yes', 4, 559, 493, 287, 189),
	array('Berlin 2', 'Coast', 'Yes', 4, 1865, 486, 287, 589),
	array('Black Sea 1', 'Sea', 'No', 0, 915, 735, 457, 300),
	array('Black Sea 2', 'Sea', 'No', 0, 2239, 725, 457, 700),
	array('Bohemia 1', 'Land', 'No', 5, 567, 586, 298, 227),
	array('Bohemia 2', 'Land', 'No', 5, 1870, 578, 298, 627),
	array('Brest 1', 'Coast', 'Yes', 2, 298, 595, 153, 240),
	array('Brest 2', 'Coast', 'Yes', 2, 1599, 581, 153, 640),
	array('Budapest 1', 'Land', 'Yes', 5, 661, 678, 350, 260),
	array('Budapest 2', 'Land', 'Yes', 5, 1974, 664, 350, 660),
	array('Bulgaria 1', 'Coast', 'Yes', 0, 730, 776, 394, 318),
	array('Bulgaria 1 (North Coast)', 'Coast', 'No', 0, 785, 762, 424, 304),
	array('Bulgaria 1 (South Coast)', 'Coast', 'No', 0, 749, 815, 397, 332),
	array('Bulgaria 2', 'Coast', 'Yes', 0, 2046, 765, 394, 718),
	array('Bulgaria 2 (North Coast)', 'Coast', 'No', 0, 2087, 762, 424, 704),
	array('Bulgaria 2 (South Coast)', 'Coast', 'No', 0, 2060, 813, 397, 732),
	array('Burgundy 1', 'Land', 'No', 2, 393, 629, 204, 243),
	array('Burgundy 2', 'Land', 'No', 2, 1713, 619, 204, 643),
	array('Clyde 1', 'Coast', 'No', 1, 309, 337, 157, 120),
	array('Clyde 2', 'Coast', 'No', 1, 1608, 319, 157, 520),
	array('Constantinople 1', 'Coast', 'Yes', 6, 821, 840, 433, 345),
	array('Constantinople 2', 'Coast', 'Yes', 6, 2134, 827, 433, 745),
	array('Denmark 1', 'Coast', 'Yes', 0, 501, 435, 265, 150),
	array('Denmark 2', 'Coast', 'Yes', 0, 1803, 434, 265, 550),
	array('Eastern Mediterranean 1', 'Sea', 'No', 0, 860, 967, 465, 383),
	array('Eastern Mediterranean 2', 'Sea', 'No', 0, 2177, 958, 465, 783),
	array('Edinburgh 1', 'Coast', 'Yes', 1, 340, 350, 175, 109),
	array('Edinburgh 2', 'Coast', 'Yes', 1, 1650, 339, 175, 509),
	array('English Channel 1', 'Sea', 'No', 0, 275, 526, 145, 205),
	array('English Channel 2', 'Sea', 'No', 0, 1589, 520, 145, 605),
	array('Finland 1', 'Coast', 'No', 7, 710, 263, 369, 109),
	array('Finland 2', 'Coast', 'No', 7, 2005, 256, 369, 509),
	array('Galicia 1', 'Land', 'No', 5, 710, 610, 378, 240),
	array('Galicia 2', 'Land', 'No', 5, 2025, 611, 378, 640),
	array('Gascony 1', 'Coast', 'No', 2, 301, 676, 154, 265),
	array('Gascony 2', 'Coast', 'No', 2, 1601, 664, 154, 665),
	array('Greece 1', 'Coast', 'Yes', 0, 676, 851, 364, 375),
	array('Greece 2', 'Coast', 'Yes', 0, 1985, 842, 364, 775),
	array('Gulf of Bothnia 1', 'Sea', 'No', 0, 653, 330, 345, 141),
	array('Gulf of Bothnia 2', 'Sea', 'No', 0, 1961, 323, 345, 541),
	array('Gulf of Lyons 1', 'Sea', 'No', 0, 366, 774, 208, 322),
	array('Gulf of Lyons 2', 'Sea', 'No', 0, 1679, 768, 208, 722),
	array('Heligoland Bight 1', 'Sea', 'No', 0, 455, 439, 241, 159),
	array('Heligoland Bight 2', 'Sea', 'No', 0, 1762, 432, 241, 559),
	array('Holland 1', 'Coast', 'Yes', 0, 433, 510, 234, 185),
	array('Holland 2', 'Coast', 'Yes', 0, 1739, 505, 234, 585),
	array('Ionian Sea 1', 'Sea', 'No', 0, 610, 952, 325, 379),
	array('Ionian Sea 2', 'Sea', 'No', 0, 1914, 941, 325, 779),
	array('Irish Sea 1', 'Sea', 'No', 0, 208, 478, 118, 171),
	array('Irish Sea 2', 'Sea', 'No', 0, 1526, 470, 118, 571),
	array('Kiel 1', 'Coast', 'Yes', 4, 477, 504, 253, 193),
	array('Kiel 2', 'Coast', 'Yes', 4, 1784, 495, 253, 593),
	array('Liverpool 1', 'Coast', 'Yes', 1, 315, 405, 166, 140),
	array('Liverpool 2', 'Coast', 'Yes', 1, 1625, 402, 166, 540),
	array('Livonia 1', 'Coast', 'No', 7, 719, 441, 374, 168),
	array('Livonia 2', 'Coast', 'No', 7, 2025, 431, 374, 568),
	array('London 1', 'Coast', 'Yes', 1, 358, 485, 176, 185),
	array('London 2', 'Coast', 'Yes', 1, 1671, 483, 176, 585),
	array('Marseilles 1', 'Coast', 'Yes', 2, 390, 689, 199, 275),
	array('Marseilles 2', 'Coast', 'Yes', 2, 1702, 682, 199, 675),
	array('Mid-Atlantic Ocean 1', 'Sea', 'No', 0, 106, 587, 60, 251),
	array('Mid-Atlantic Ocean 2', 'Sea', 'No', 0, 1411, 567, 60, 651),
	array('Moscow 1', 'Land', 'Yes', 7, 880, 440, 490, 160),
	array('Moscow 2', 'Land', 'Yes', 7, 2182, 427, 490, 560),
	array('Munich 1', 'Land', 'Yes', 4, 489, 596, 252, 229),
	array('Munich 2', 'Land', 'Yes', 4, 1797, 590, 252, 629),
	array('Naples 1', 'Coast', 'Yes', 3, 570, 870, 298, 357),
	array('Naples 2', 'Coast', 'Yes', 3, 1879, 872, 298, 757),
	array('North Africa 1', 'Coast', 'No', 0, 210, 923, 130, 380),
	array('North Africa 2', 'Coast', 'No', 0, 1529, 917, 130, 780),
	array('North Atlantic Ocean 1', 'Sea', 'No', 0, 163, 224, 78, 92),
	array('North Atlantic Ocean 2', 'Sea', 'No', 0, 1470, 224, 78, 492),
	array('North Sea 1', 'Sea', 'No', 0, 414, 378, 216, 125),
	array('North Sea 2', 'Sea', 'No', 0, 1730, 369, 216, 525),
	array('Norway 1', 'Coast', 'Yes', 0, 518, 270, 265, 113),
	array('Norway 2', 'Coast', 'Yes', 0, 1832, 255, 265, 513),
	array('Norwegian Sea 1', 'Sea', 'No', 0, 437, 149, 240, 31),
	array('Norwegian Sea 2', 'Sea', 'No', 0, 1740, 135, 240, 431),
	array('Paris 1', 'Land', 'Yes', 2, 336, 620, 176, 233),
	array('Paris 2', 'Land', 'Yes', 2, 1640, 620, 176, 633),
	array('Picardy 1', 'Coast', 'No', 2, 363, 559, 182, 213),
	array('Picardy 2', 'Coast', 'No', 2, 1667, 552, 182, 613),
	array('Piedmont 1', 'Coast', 'No', 3, 441, 694, 228, 276),
	array('Piedmont 2', 'Coast', 'No', 3, 1747, 688, 228, 676),
	array('Portugal 1', 'Coast', 'Yes', 0, 100, 718, 65, 292),
	array('Portugal 2', 'Coast', 'Yes', 0, 1416, 710, 65, 692),
	array('Prussia 1', 'Coast', 'No', 4, 618, 482, 319, 202),
	array('Prussia 2', 'Coast', 'No', 4, 1921, 479, 319, 602),
	array('Rome 1', 'Coast', 'Yes', 3, 522, 800, 272, 330),
	array('Rome 2', 'Coast', 'Yes', 3, 1831, 799, 272, 730),
	array('Ruhr 1', 'Land', 'No', 4, 450, 550, 227, 221),
	array('Ruhr 2', 'Land', 'No', 4, 1755, 548, 227, 621),
	array('Rumania 1', 'Coast', 'Yes', 0, 765, 717, 412, 272),
	array('Rumania 2', 'Coast', 'Yes', 0, 2083, 714, 412, 672),
	array('Serbia 1', 'Land', 'Yes', 0, 668, 766, 357, 324),
	array('Serbia 2', 'Land', 'Yes', 0, 1979, 756, 357, 724),
	array('Sevastopol 1', 'Coast', 'Yes', 7, 920, 595, 485, 248),
	array('Sevastopol 2', 'Coast', 'Yes', 7, 2289, 594, 485, 648),
	array('Silesia 1', 'Land', 'No', 4, 589, 535, 315, 222),
	array('Silesia 2', 'Land', 'No', 4, 1888, 532, 315, 622),
	array('Skagerrack 1', 'Sea', 'No', 0, 518, 363, 284, 146),
	array('Skagerrack 2', 'Sea', 'No', 0, 1821, 361, 284, 546),
	array('Smyrna 1', 'Coast', 'Yes', 6, 899, 890, 480, 363),
	array('Smyrna 2', 'Coast', 'Yes', 6, 2223, 884, 480, 763),
	array('Spain 1', 'Coast', 'Yes', 0, 205, 760, 110, 307),
	array('Spain 1 (North Coast)', 'Coast', 'No', 0, 193, 685, 90, 273),
	array('Spain 1 (South Coast)', 'Coast', 'No', 0, 191, 832, 106, 345),
	array('Spain 2', 'Coast', 'Yes', 0, 1529, 751, 110, 707),
	array('Spain 2 (North Coast)', 'Coast', 'No', 0, 1499, 694, 90, 673),
	array('Spain 2 (South Coast)', 'Coast', 'No', 0, 1505, 823, 106, 745),
	array('St. Petersburg 1', 'Coast', 'Yes', 7, 837, 309, 445, 97),
	array('St. Petersburg 1 (North Coast)', 'Coast', 'No', 7, 828, 90, 448, 59),
	array('St. Petersburg 1 (South Coast)', 'Coast', 'No', 7, 760, 335, 397, 130),
	array('St. Petersburg 2', 'Coast', 'Yes', 7, 2139, 306, 445, 497),
	array('St. Petersburg 2 (North Coast)', 'Coast', 'No', 7, 2139, 107, 448, 459),
	array('St. Petersburg 2 (South Coast)', 'Coast', 'No', 7, 2071, 339, 397, 530),
	array('Sweden 1', 'Coast', 'Yes', 0, 587, 285, 307, 103),
	array('Sweden 2', 'Coast', 'Yes', 0, 1900, 274, 307, 503),
	array('Syria 1', 'Coast', 'No', 6, 1073, 940, 559, 370),
	array('Syria 2', 'Coast', 'No', 6, 2349, 929, 559, 770),
	array('Trieste 1', 'Coast', 'Yes', 5, 579, 710, 308, 288),
	array('Trieste 2', 'Coast', 'Yes', 5, 1890, 705, 308, 688),
	array('Tunis 1', 'Coast', 'Yes', 0, 420, 970, 204, 384),
	array('Tunis 2', 'Coast', 'Yes', 0, 1735, 966, 204, 784),
	array('Tuscany 1', 'Coast', 'No', 3, 485, 755, 256, 312),
	array('Tuscany 2', 'Coast', 'No', 3, 1786, 751, 256, 712),
	array('Tyrolia 1', 'Land', 'No', 5, 542, 632, 282, 252),
	array('Tyrolia 2', 'Land', 'No', 5, 1855, 631, 282, 652),
	array('Tyrrhenian Sea 1', 'Sea', 'No', 0, 480, 847, 248, 343),
	array('Tyrrhenian Sea 2', 'Sea', 'No', 0, 1786, 842, 248, 743),
	array('Ukraine 1', 'Land', 'No', 7, 779, 579, 418, 220),
	array('Ukraine 2', 'Land', 'No', 7, 2084, 569, 418, 620),
	array('Venice 1', 'Coast', 'Yes', 3, 490, 710, 258, 292),
	array('Venice 2', 'Coast', 'Yes', 3, 1799, 705, 258, 692),
	array('Vienna 1', 'Land', 'Yes', 5, 602, 637, 314, 246),
	array('Vienna 2', 'Land', 'Yes', 5, 1912, 630, 314, 646),
	array('Wales 1', 'Coast', 'No', 1, 305, 480, 154, 179),
	array('Wales 2', 'Coast', 'No', 1, 1601, 467, 154, 579),
	array('Warsaw 1', 'Land', 'Yes', 7, 680, 540, 358, 209),
	array('Warsaw 2', 'Land', 'Yes', 7, 1989, 531, 358, 609),
	array('Western Mediterranean 1', 'Sea', 'No', 0, 327, 852, 186, 350),
	array('Western Mediterranean 2', 'Sea', 'No', 0, 1639, 842, 186, 750),
	array('Yorkshire 1', 'Coast', 'No', 1, 355, 440, 184, 150),
	array('Yorkshire 2', 'Coast', 'No', 1, 1657, 432, 184, 550)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Adriatic Sea 1','Adriatic Sea 2','Yes','No'),
	array('Adriatic Sea 1','Albania 1','Yes','No'),
	array('Adriatic Sea 1','Apulia 1','Yes','No'),
	array('Adriatic Sea 1','Ionian Sea 1','Yes','No'),
	array('Adriatic Sea 1','Trieste 1','Yes','No'),
	array('Adriatic Sea 1','Venice 1','Yes','No'),
	array('Adriatic Sea 2','Albania 2','Yes','No'),
	array('Adriatic Sea 2','Apulia 2','Yes','No'),
	array('Adriatic Sea 2','Ionian Sea 2','Yes','No'),
	array('Adriatic Sea 2','Trieste 2','Yes','No'),
	array('Adriatic Sea 2','Venice 2','Yes','No'),
	array('Aegean Sea 1','Aegean Sea 2','Yes','No'),
	array('Aegean Sea 1','Bulgaria 1 (South Coast)','Yes','No'),
	array('Aegean Sea 1','Constantinople 1','Yes','No'),
	array('Aegean Sea 1','Eastern Mediterranean 1','Yes','No'),
	array('Aegean Sea 1','Greece 1','Yes','No'),
	array('Aegean Sea 1','Ionian Sea 1','Yes','No'),
	array('Aegean Sea 1','Smyrna 1','Yes','No'),
	array('Aegean Sea 2','Bulgaria 2 (South Coast)','Yes','No'),
	array('Aegean Sea 2','Constantinople 2','Yes','No'),
	array('Aegean Sea 2','Eastern Mediterranean 2','Yes','No'),
	array('Aegean Sea 2','Greece 2','Yes','No'),
	array('Aegean Sea 2','Ionian Sea 2','Yes','No'),
	array('Aegean Sea 2','Smyrna 2','Yes','No'),
	array('Albania 1','Albania 2','Yes','Yes'),
	array('Albania 1','Greece 1','Yes','Yes'),
	array('Albania 1','Ionian Sea 1','Yes','No'),
	array('Albania 1','Serbia 1','No','Yes'),
	array('Albania 1','Trieste 1','Yes','Yes'),
	array('Albania 2','Greece 2','Yes','Yes'),
	array('Albania 2','Ionian Sea 2','Yes','No'),
	array('Albania 2','Serbia 2','No','Yes'),
	array('Albania 2','Trieste 2','Yes','Yes'),
	array('Ankara 1','Ankara 2','Yes','Yes'),
	array('Ankara 1','Armenia 1','Yes','Yes'),
	array('Ankara 1','Black Sea 1','Yes','No'),
	array('Ankara 1','Constantinople 1','Yes','Yes'),
	array('Ankara 1','Smyrna 1','No','Yes'),
	array('Ankara 2','Armenia 2','Yes','Yes'),
	array('Ankara 2','Black Sea 2','Yes','No'),
	array('Ankara 2','Constantinople 2','Yes','Yes'),
	array('Ankara 2','Smyrna 2','No','Yes'),
	array('Apulia 1','Apulia 2','Yes','Yes'),
	array('Apulia 1','Ionian Sea 1','Yes','No'),
	array('Apulia 1','Naples 1','Yes','Yes'),
	array('Apulia 1','Rome 1','No','Yes'),
	array('Apulia 1','Venice 1','Yes','Yes'),
	array('Apulia 2','Ionian Sea 2','Yes','No'),
	array('Apulia 2','Naples 2','Yes','Yes'),
	array('Apulia 2','Rome 2','No','Yes'),
	array('Apulia 2','Venice 2','Yes','Yes'),
	array('Armenia 1','Armenia 2','Yes','Yes'),
	array('Armenia 1','Black Sea 1','Yes','No'),
	array('Armenia 1','Sevastopol 1','Yes','Yes'),
	array('Armenia 1','Smyrna 1','No','Yes'),
	array('Armenia 1','Syria 1','No','Yes'),
	array('Armenia 2','Black Sea 2','Yes','No'),
	array('Armenia 2','Sevastopol 2','Yes','Yes'),
	array('Armenia 2','Smyrna 2','No','Yes'),
	array('Armenia 2','Syria 2','No','Yes'),
	array('Baltic Sea 1','Baltic Sea 2','Yes','No'),
	array('Baltic Sea 1','Berlin 1','Yes','No'),
	array('Baltic Sea 1','Denmark 1','Yes','No'),
	array('Baltic Sea 1','Gulf of Bothnia 1','Yes','No'),
	array('Baltic Sea 1','Kiel 1','Yes','No'),
	array('Baltic Sea 1','Livonia 1','Yes','No'),
	array('Baltic Sea 1','Prussia 1','Yes','No'),
	array('Baltic Sea 1','Sweden 1','Yes','No'),
	array('Baltic Sea 2','Berlin 2','Yes','No'),
	array('Baltic Sea 2','Denmark 2','Yes','No'),
	array('Baltic Sea 2','Gulf of Bothnia 2','Yes','No'),
	array('Baltic Sea 2','Kiel 2','Yes','No'),
	array('Baltic Sea 2','Livonia 2','Yes','No'),
	array('Baltic Sea 2','Prussia 2','Yes','No'),
	array('Baltic Sea 2','Sweden 2','Yes','No'),
	array('Barents Sea 1','Barents Sea 2','Yes','No'),
	array('Barents Sea 1','Norway 1','Yes','No'),
	array('Barents Sea 1','Norwegian Sea 1','Yes','No'),
	array('Barents Sea 1','St. Petersburg 1 (North Coast)','Yes','No'),
	array('Barents Sea 2','Norway 2','Yes','No'),
	array('Barents Sea 2','Norwegian Sea 2','Yes','No'),
	array('Barents Sea 2','St. Petersburg 2 (North Coast)','Yes','No'),
	array('Belgium 1','Belgium 2','Yes','Yes'),
	array('Belgium 1','Burgundy 1','No','Yes'),
	array('Belgium 1','English Channel 1','Yes','No'),
	array('Belgium 1','Holland 1','Yes','Yes'),
	array('Belgium 1','North Sea 1','Yes','No'),
	array('Belgium 1','Picardy 1','Yes','Yes'),
	array('Belgium 1','Ruhr 1','No','Yes'),
	array('Belgium 2','Burgundy 2','No','Yes'),
	array('Belgium 2','English Channel 2','Yes','No'),
	array('Belgium 2','Holland 2','Yes','Yes'),
	array('Belgium 2','North Sea 2','Yes','No'),
	array('Belgium 2','Picardy 2','Yes','Yes'),
	array('Belgium 2','Ruhr 2','No','Yes'),
	array('Berlin 1','Berlin 2','Yes','Yes'),
	array('Berlin 1','Kiel 1','Yes','Yes'),
	array('Berlin 1','Munich 1','No','Yes'),
	array('Berlin 1','Prussia 1','Yes','Yes'),
	array('Berlin 1','Silesia 1','No','Yes'),
	array('Berlin 2','Kiel 2','Yes','Yes'),
	array('Berlin 2','Munich 2','No','Yes'),
	array('Berlin 2','Prussia 2','Yes','Yes'),
	array('Berlin 2','Silesia 2','No','Yes'),
	array('Black Sea 1','Black Sea 2','Yes','No'),
	array('Black Sea 1','Bulgaria 1 (North Coast)','Yes','No'),
	array('Black Sea 1','Constantinople 1','Yes','No'),
	array('Black Sea 1','Rumania 1','Yes','No'),
	array('Black Sea 1','Sevastopol 1','Yes','No'),
	array('Black Sea 2','Bulgaria 2 (North Coast)','Yes','No'),
	array('Black Sea 2','Constantinople 2','Yes','No'),
	array('Black Sea 2','Rumania 2','Yes','No'),
	array('Black Sea 2','Sevastopol 2','Yes','No'),
	array('Bohemia 1','Bohemia 2','No','Yes'),
	array('Bohemia 1','Galicia 1','No','Yes'),
	array('Bohemia 1','Munich 1','No','Yes'),
	array('Bohemia 1','Silesia 1','No','Yes'),
	array('Bohemia 1','Tyrolia 1','No','Yes'),
	array('Bohemia 1','Vienna 1','No','Yes'),
	array('Bohemia 2','Galicia 2','No','Yes'),
	array('Bohemia 2','Munich 2','No','Yes'),
	array('Bohemia 2','Silesia 2','No','Yes'),
	array('Bohemia 2','Tyrolia 2','No','Yes'),
	array('Bohemia 2','Vienna 2','No','Yes'),
	array('Brest 1','Brest 2','Yes','Yes'),
	array('Brest 1','English Channel 1','Yes','No'),
	array('Brest 1','Gascony 1','Yes','Yes'),
	array('Brest 1','Mid-Atlantic Ocean 1','Yes','No'),
	array('Brest 1','Paris 1','No','Yes'),
	array('Brest 1','Picardy 1','Yes','Yes'),
	array('Brest 2','English Channel 2','Yes','No'),
	array('Brest 2','Gascony 2','Yes','Yes'),
	array('Brest 2','Mid-Atlantic Ocean 2','Yes','No'),
	array('Brest 2','Paris 2','No','Yes'),
	array('Brest 2','Picardy 2','Yes','Yes'),
	array('Budapest 1','Budapest 2','No','Yes'),
	array('Budapest 1','Galicia 1','No','Yes'),
	array('Budapest 1','Rumania 1','No','Yes'),
	array('Budapest 1','Serbia 1','No','Yes'),
	array('Budapest 1','Trieste 1','No','Yes'),
	array('Budapest 1','Vienna 1','No','Yes'),
	array('Budapest 2','Galicia 2','No','Yes'),
	array('Budapest 2','Rumania 2','No','Yes'),
	array('Budapest 2','Serbia 2','No','Yes'),
	array('Budapest 2','Trieste 2','No','Yes'),
	array('Budapest 2','Vienna 2','No','Yes'),
	array('Bulgaria 1','Bulgaria 2','No','Yes'),
	array('Bulgaria 1','Constantinople 1','No','Yes'),
	array('Bulgaria 1','Greece 1','No','Yes'),
	array('Bulgaria 1','Rumania 1','No','Yes'),
	array('Bulgaria 1','Serbia 1','No','Yes'),
	array('Bulgaria 1 (North Coast)','Bulgaria 2 (North Coast)','Yes','No'),
	array('Bulgaria 1 (North Coast)','Constantinople 1','Yes','No'),
	array('Bulgaria 1 (North Coast)','Rumania 1','Yes','No'),
	array('Bulgaria 1 (South Coast)','Bulgaria 2 (South Coast)','Yes','No'),
	array('Bulgaria 1 (South Coast)','Constantinople 1','Yes','No'),
	array('Bulgaria 1 (South Coast)','Greece 1','Yes','No'),
	array('Bulgaria 2','Constantinople 2','No','Yes'),
	array('Bulgaria 2','Greece 2','No','Yes'),
	array('Bulgaria 2','Rumania 2','No','Yes'),
	array('Bulgaria 2','Serbia 2','No','Yes'),
	array('Bulgaria 2 (North Coast)','Constantinople 2','Yes','No'),
	array('Bulgaria 2 (North Coast)','Rumania 2','Yes','No'),
	array('Bulgaria 2 (South Coast)','Constantinople 2','Yes','No'),
	array('Bulgaria 2 (South Coast)','Greece 2','Yes','No'),
	array('Burgundy 1','Burgundy 2','No','Yes'),
	array('Burgundy 1','Gascony 1','No','Yes'),
	array('Burgundy 1','Marseilles 1','No','Yes'),
	array('Burgundy 1','Munich 1','No','Yes'),
	array('Burgundy 1','Paris 1','No','Yes'),
	array('Burgundy 1','Picardy 1','No','Yes'),
	array('Burgundy 1','Ruhr 1','No','Yes'),
	array('Burgundy 2','Gascony 2','No','Yes'),
	array('Burgundy 2','Marseilles 2','No','Yes'),
	array('Burgundy 2','Munich 2','No','Yes'),
	array('Burgundy 2','Paris 2','No','Yes'),
	array('Burgundy 2','Picardy 2','No','Yes'),
	array('Burgundy 2','Ruhr 2','No','Yes'),
	array('Clyde 1','Clyde 2','Yes','Yes'),
	array('Clyde 1','Edinburgh 1','Yes','Yes'),
	array('Clyde 1','Liverpool 1','Yes','Yes'),
	array('Clyde 1','North Atlantic Ocean 1','Yes','No'),
	array('Clyde 1','Norwegian Sea 1','Yes','No'),
	array('Clyde 2','Edinburgh 2','Yes','Yes'),
	array('Clyde 2','Liverpool 2','Yes','Yes'),
	array('Clyde 2','North Atlantic Ocean 2','Yes','No'),
	array('Clyde 2','Norwegian Sea 2','Yes','No'),
	array('Constantinople 1','Constantinople 2','Yes','Yes'),
	array('Constantinople 1','Smyrna 1','Yes','Yes'),
	array('Constantinople 2','Smyrna 2','Yes','Yes'),
	array('Denmark 1','Denmark 2','Yes','Yes'),
	array('Denmark 1','Heligoland Bight 1','Yes','No'),
	array('Denmark 1','Kiel 1','Yes','Yes'),
	array('Denmark 1','North Sea 1','Yes','No'),
	array('Denmark 1','Skagerrack 1','Yes','No'),
	array('Denmark 1','Sweden 1','Yes','Yes'),
	array('Denmark 2','Heligoland Bight 2','Yes','No'),
	array('Denmark 2','Kiel 2','Yes','Yes'),
	array('Denmark 2','North Sea 2','Yes','No'),
	array('Denmark 2','Skagerrack 2','Yes','No'),
	array('Denmark 2','Sweden 2','Yes','Yes'),
	array('Eastern Mediterranean 1','Eastern Mediterranean 2','Yes','No'),
	array('Eastern Mediterranean 1','Ionian Sea 1','Yes','No'),
	array('Eastern Mediterranean 1','Smyrna 1','Yes','No'),
	array('Eastern Mediterranean 1','Syria 1','Yes','No'),
	array('Eastern Mediterranean 2','Ionian Sea 2','Yes','No'),
	array('Eastern Mediterranean 2','Smyrna 2','Yes','No'),
	array('Eastern Mediterranean 2','Syria 2','Yes','No'),
	array('Edinburgh 1','Edinburgh 2','Yes','Yes'),
	array('Edinburgh 1','Liverpool 1','No','Yes'),
	array('Edinburgh 1','North Sea 1','Yes','No'),
	array('Edinburgh 1','Norwegian Sea 1','Yes','No'),
	array('Edinburgh 1','Yorkshire 1','Yes','Yes'),
	array('Edinburgh 2','Liverpool 2','No','Yes'),
	array('Edinburgh 2','North Sea 2','Yes','No'),
	array('Edinburgh 2','Norwegian Sea 2','Yes','No'),
	array('Edinburgh 2','Yorkshire 2','Yes','Yes'),
	array('English Channel 1','English Channel 2','Yes','No'),
	array('English Channel 1','Irish Sea 1','Yes','No'),
	array('English Channel 1','London 1','Yes','No'),
	array('English Channel 1','Mid-Atlantic Ocean 1','Yes','No'),
	array('English Channel 1','North Sea 1','Yes','No'),
	array('English Channel 1','Picardy 1','Yes','No'),
	array('English Channel 1','Wales 1','Yes','No'),
	array('English Channel 2','Irish Sea 2','Yes','No'),
	array('English Channel 2','London 2','Yes','No'),
	array('English Channel 2','Mid-Atlantic Ocean 2','Yes','No'),
	array('English Channel 2','North Sea 2','Yes','No'),
	array('English Channel 2','Picardy 2','Yes','No'),
	array('English Channel 2','Wales 2','Yes','No'),
	array('Finland 1','Finland 2','Yes','Yes'),
	array('Finland 1','Gulf of Bothnia 1','Yes','No'),
	array('Finland 1','Norway 1','No','Yes'),
	array('Finland 1','St. Petersburg 1','No','Yes'),
	array('Finland 1','St. Petersburg 1 (South Coast)','Yes','No'),
	array('Finland 1','Sweden 1','Yes','Yes'),
	array('Finland 2','Gulf of Bothnia 2','Yes','No'),
	array('Finland 2','Norway 2','No','Yes'),
	array('Finland 2','St. Petersburg 2','No','Yes'),
	array('Finland 2','St. Petersburg 2 (South Coast)','Yes','No'),
	array('Finland 2','Sweden 2','Yes','Yes'),
	array('Galicia 1','Galicia 2','No','Yes'),
	array('Galicia 1','Rumania 1','No','Yes'),
	array('Galicia 1','Silesia 1','No','Yes'),
	array('Galicia 1','Ukraine 1','No','Yes'),
	array('Galicia 1','Vienna 1','No','Yes'),
	array('Galicia 1','Warsaw 1','No','Yes'),
	array('Galicia 2','Rumania 2','No','Yes'),
	array('Galicia 2','Silesia 2','No','Yes'),
	array('Galicia 2','Ukraine 2','No','Yes'),
	array('Galicia 2','Vienna 2','No','Yes'),
	array('Galicia 2','Warsaw 2','No','Yes'),
	array('Gascony 1','Gascony 2','Yes','Yes'),
	array('Gascony 1','Marseilles 1','No','Yes'),
	array('Gascony 1','Mid-Atlantic Ocean 1','Yes','No'),
	array('Gascony 1','Paris 1','No','Yes'),
	array('Gascony 1','Spain 1','No','Yes'),
	array('Gascony 1','Spain 1 (North Coast)','Yes','No'),
	array('Gascony 2','Marseilles 2','No','Yes'),
	array('Gascony 2','Mid-Atlantic Ocean 2','Yes','No'),
	array('Gascony 2','Paris 2','No','Yes'),
	array('Gascony 2','Spain 2','No','Yes'),
	array('Gascony 2','Spain 2 (North Coast)','Yes','No'),
	array('Greece 1','Greece 2','Yes','Yes'),
	array('Greece 1','Ionian Sea 1','Yes','No'),
	array('Greece 1','Serbia 1','No','Yes'),
	array('Greece 2','Ionian Sea 2','Yes','No'),
	array('Greece 2','Serbia 2','No','Yes'),
	array('Gulf of Bothnia 1','Gulf of Bothnia 2','Yes','No'),
	array('Gulf of Bothnia 1','Livonia 1','Yes','No'),
	array('Gulf of Bothnia 1','St. Petersburg 1 (South Coast)','Yes','No'),
	array('Gulf of Bothnia 1','Sweden 1','Yes','No'),
	array('Gulf of Bothnia 2','Livonia 2','Yes','No'),
	array('Gulf of Bothnia 2','St. Petersburg 2 (South Coast)','Yes','No'),
	array('Gulf of Bothnia 2','Sweden 2','Yes','No'),
	array('Gulf of Lyons 1','Gulf of Lyons 2','Yes','No'),
	array('Gulf of Lyons 1','Marseilles 1','Yes','No'),
	array('Gulf of Lyons 1','Piedmont 1','Yes','No'),
	array('Gulf of Lyons 1','Spain 1 (South Coast)','Yes','No'),
	array('Gulf of Lyons 1','Tuscany 1','Yes','No'),
	array('Gulf of Lyons 1','Tyrrhenian Sea 1','Yes','No'),
	array('Gulf of Lyons 1','Western Mediterranean 1','Yes','No'),
	array('Gulf of Lyons 2','Marseilles 2','Yes','No'),
	array('Gulf of Lyons 2','Piedmont 2','Yes','No'),
	array('Gulf of Lyons 2','Spain 2 (South Coast)','Yes','No'),
	array('Gulf of Lyons 2','Tuscany 2','Yes','No'),
	array('Gulf of Lyons 2','Tyrrhenian Sea 2','Yes','No'),
	array('Gulf of Lyons 2','Western Mediterranean 2','Yes','No'),
	array('Heligoland Bight 1','Heligoland Bight 2','Yes','No'),
	array('Heligoland Bight 1','Holland 1','Yes','No'),
	array('Heligoland Bight 1','Kiel 1','Yes','No'),
	array('Heligoland Bight 1','North Sea 1','Yes','No'),
	array('Heligoland Bight 2','Holland 2','Yes','No'),
	array('Heligoland Bight 2','Kiel 2','Yes','No'),
	array('Heligoland Bight 2','North Sea 2','Yes','No'),
	array('Holland 1','Holland 2','Yes','Yes'),
	array('Holland 1','Kiel 1','Yes','Yes'),
	array('Holland 1','North Sea 1','Yes','No'),
	array('Holland 1','Ruhr 1','No','Yes'),
	array('Holland 2','Kiel 2','Yes','Yes'),
	array('Holland 2','North Sea 2','Yes','No'),
	array('Holland 2','Ruhr 2','No','Yes'),
	array('Ionian Sea 1','Ionian Sea 2','Yes','No'),
	array('Ionian Sea 1','Naples 1','Yes','No'),
	array('Ionian Sea 1','Tunis 1','Yes','No'),
	array('Ionian Sea 1','Tyrrhenian Sea 1','Yes','No'),
	array('Ionian Sea 2','Naples 2','Yes','No'),
	array('Ionian Sea 2','Tunis 2','Yes','No'),
	array('Ionian Sea 2','Tyrrhenian Sea 2','Yes','No'),
	array('Irish Sea 1','Irish Sea 2','Yes','No'),
	array('Irish Sea 1','Liverpool 1','Yes','No'),
	array('Irish Sea 1','Mid-Atlantic Ocean 1','Yes','No'),
	array('Irish Sea 1','North Atlantic Ocean 1','Yes','No'),
	array('Irish Sea 1','Wales 1','Yes','No'),
	array('Irish Sea 2','Liverpool 2','Yes','No'),
	array('Irish Sea 2','Mid-Atlantic Ocean 2','Yes','No'),
	array('Irish Sea 2','North Atlantic Ocean 2','Yes','No'),
	array('Irish Sea 2','Wales 2','Yes','No'),
	array('Kiel 1','Kiel 2','Yes','Yes'),
	array('Kiel 1','Munich 1','No','Yes'),
	array('Kiel 1','Ruhr 1','No','Yes'),
	array('Kiel 2','Munich 2','No','Yes'),
	array('Kiel 2','Ruhr 2','No','Yes'),
	array('Liverpool 1','Liverpool 2','Yes','Yes'),
	array('Liverpool 1','North Atlantic Ocean 1','Yes','No'),
	array('Liverpool 1','Wales 1','Yes','Yes'),
	array('Liverpool 1','Yorkshire 1','No','Yes'),
	array('Liverpool 2','North Atlantic Ocean 2','Yes','No'),
	array('Liverpool 2','Wales 2','Yes','Yes'),
	array('Liverpool 2','Yorkshire 2','No','Yes'),
	array('Livonia 1','Livonia 2','Yes','Yes'),
	array('Livonia 1','Moscow 1','No','Yes'),
	array('Livonia 1','Prussia 1','Yes','Yes'),
	array('Livonia 1','St. Petersburg 1','No','Yes'),
	array('Livonia 1','St. Petersburg 1 (South Coast)','Yes','No'),
	array('Livonia 1','Warsaw 1','No','Yes'),
	array('Livonia 2','Moscow 2','No','Yes'),
	array('Livonia 2','Prussia 2','Yes','Yes'),
	array('Livonia 2','St. Petersburg 2','No','Yes'),
	array('Livonia 2','St. Petersburg 2 (South Coast)','Yes','No'),
	array('Livonia 2','Warsaw 2','No','Yes'),
	array('London 1','London 2','Yes','Yes'),
	array('London 1','North Sea 1','Yes','No'),
	array('London 1','Wales 1','Yes','Yes'),
	array('London 1','Yorkshire 1','Yes','Yes'),
	array('London 2','North Sea 2','Yes','No'),
	array('London 2','Wales 2','Yes','Yes'),
	array('London 2','Yorkshire 2','Yes','Yes'),
	array('Marseilles 1','Marseilles 2','Yes','Yes'),
	array('Marseilles 1','Piedmont 1','Yes','Yes'),
	array('Marseilles 1','Spain 1','No','Yes'),
	array('Marseilles 1','Spain 1 (South Coast)','Yes','No'),
	array('Marseilles 2','Piedmont 2','Yes','Yes'),
	array('Marseilles 2','Spain 2','No','Yes'),
	array('Marseilles 2','Spain 2 (South Coast)','Yes','No'),
	array('Mid-Atlantic Ocean 1','Mid-Atlantic Ocean 2','Yes','No'),
	array('Mid-Atlantic Ocean 1','North Africa 1','Yes','No'),
	array('Mid-Atlantic Ocean 1','North Atlantic Ocean 1','Yes','No'),
	array('Mid-Atlantic Ocean 1','Portugal 1','Yes','No'),
	array('Mid-Atlantic Ocean 1','Spain 1 (North Coast)','Yes','No'),
	array('Mid-Atlantic Ocean 1','Spain 1 (South Coast)','Yes','No'),
	array('Mid-Atlantic Ocean 1','Western Mediterranean 1','Yes','No'),
	array('Mid-Atlantic Ocean 2','North Africa 2','Yes','No'),
	array('Mid-Atlantic Ocean 2','North Atlantic Ocean 2','Yes','No'),
	array('Mid-Atlantic Ocean 2','Portugal 2','Yes','No'),
	array('Mid-Atlantic Ocean 2','Spain 2 (North Coast)','Yes','No'),
	array('Mid-Atlantic Ocean 2','Spain 2 (South Coast)','Yes','No'),
	array('Mid-Atlantic Ocean 2','Western Mediterranean 2','Yes','No'),
	array('Moscow 1','Moscow 2','No','Yes'),
	array('Moscow 1','Sevastopol 1','No','Yes'),
	array('Moscow 1','St. Petersburg 1','No','Yes'),
	array('Moscow 1','Ukraine 1','No','Yes'),
	array('Moscow 1','Warsaw 1','No','Yes'),
	array('Moscow 2','Sevastopol 2','No','Yes'),
	array('Moscow 2','St. Petersburg 2','No','Yes'),
	array('Moscow 2','Ukraine 2','No','Yes'),
	array('Moscow 2','Warsaw 2','No','Yes'),
	array('Munich 1','Munich 2','No','Yes'),
	array('Munich 1','Ruhr 1','No','Yes'),
	array('Munich 1','Silesia 1','No','Yes'),
	array('Munich 1','Tyrolia 1','No','Yes'),
	array('Munich 2','Ruhr 2','No','Yes'),
	array('Munich 2','Silesia 2','No','Yes'),
	array('Munich 2','Tyrolia 2','No','Yes'),
	array('Naples 1','Naples 2','Yes','Yes'),
	array('Naples 1','Rome 1','Yes','Yes'),
	array('Naples 1','Tyrrhenian Sea 1','Yes','No'),
	array('Naples 2','Rome 2','Yes','Yes'),
	array('Naples 2','Tyrrhenian Sea 2','Yes','No'),
	array('North Africa 1','North Africa 2','Yes','Yes'),
	array('North Africa 1','Tunis 1','Yes','Yes'),
	array('North Africa 1','Western Mediterranean 1','Yes','No'),
	array('North Africa 2','Tunis 2','Yes','Yes'),
	array('North Africa 2','Western Mediterranean 2','Yes','No'),
	array('North Atlantic Ocean 1','North Atlantic Ocean 2','Yes','No'),
	array('North Atlantic Ocean 1','Norwegian Sea 1','Yes','No'),
	array('North Atlantic Ocean 2','Norwegian Sea 2','Yes','No'),
	array('North Sea 1','North Sea 2','Yes','No'),
	array('North Sea 1','Norway 1','Yes','No'),
	array('North Sea 1','Norwegian Sea 1','Yes','No'),
	array('North Sea 1','Skagerrack 1','Yes','No'),
	array('North Sea 1','Yorkshire 1','Yes','No'),
	array('North Sea 2','Norway 2','Yes','No'),
	array('North Sea 2','Norwegian Sea 2','Yes','No'),
	array('North Sea 2','Skagerrack 2','Yes','No'),
	array('North Sea 2','Yorkshire 2','Yes','No'),
	array('Norway 1','Norway 2','Yes','Yes'),
	array('Norway 1','Norwegian Sea 1','Yes','No'),
	array('Norway 1','Skagerrack 1','Yes','No'),
	array('Norway 1','St. Petersburg 1','No','Yes'),
	array('Norway 1','St. Petersburg 1 (North Coast)','Yes','No'),
	array('Norway 1','Sweden 1','Yes','Yes'),
	array('Norway 2','Norwegian Sea 2','Yes','No'),
	array('Norway 2','Skagerrack 2','Yes','No'),
	array('Norway 2','St. Petersburg 2','No','Yes'),
	array('Norway 2','St. Petersburg 2 (North Coast)','Yes','No'),
	array('Norway 2','Sweden 2','Yes','Yes'),
	array('Norwegian Sea 1','Norwegian Sea 2','Yes','No'),
	array('Paris 1','Paris 2','No','Yes'),
	array('Paris 1','Picardy 1','No','Yes'),
	array('Paris 2','Picardy 2','No','Yes'),
	array('Picardy 1','Picardy 2','Yes','Yes'),
	array('Piedmont 1','Piedmont 2','Yes','Yes'),
	array('Piedmont 1','Tuscany 1','Yes','Yes'),
	array('Piedmont 1','Tyrolia 1','No','Yes'),
	array('Piedmont 1','Venice 1','No','Yes'),
	array('Piedmont 2','Tuscany 2','Yes','Yes'),
	array('Piedmont 2','Tyrolia 2','No','Yes'),
	array('Piedmont 2','Venice 2','No','Yes'),
	array('Portugal 1','Portugal 2','Yes','Yes'),
	array('Portugal 1','Spain 1','No','Yes'),
	array('Portugal 1','Spain 1 (North Coast)','Yes','No'),
	array('Portugal 1','Spain 1 (South Coast)','Yes','No'),
	array('Portugal 2','Spain 2','No','Yes'),
	array('Portugal 2','Spain 2 (North Coast)','Yes','No'),
	array('Portugal 2','Spain 2 (South Coast)','Yes','No'),
	array('Prussia 1','Prussia 2','Yes','Yes'),
	array('Prussia 1','Silesia 1','No','Yes'),
	array('Prussia 1','Warsaw 1','No','Yes'),
	array('Prussia 2','Silesia 2','No','Yes'),
	array('Prussia 2','Warsaw 2','No','Yes'),
	array('Rome 1','Rome 2','Yes','Yes'),
	array('Rome 1','Tuscany 1','Yes','Yes'),
	array('Rome 1','Tyrrhenian Sea 1','Yes','No'),
	array('Rome 1','Venice 1','No','Yes'),
	array('Rome 2','Tuscany 2','Yes','Yes'),
	array('Rome 2','Tyrrhenian Sea 2','Yes','No'),
	array('Rome 2','Venice 2','No','Yes'),
	array('Ruhr 1','Ruhr 2','No','Yes'),
	array('Rumania 1','Rumania 2','Yes','Yes'),
	array('Rumania 1','Serbia 1','No','Yes'),
	array('Rumania 1','Sevastopol 1','Yes','Yes'),
	array('Rumania 1','Ukraine 1','No','Yes'),
	array('Rumania 2','Serbia 2','No','Yes'),
	array('Rumania 2','Sevastopol 2','Yes','Yes'),
	array('Rumania 2','Ukraine 2','No','Yes'),
	array('Serbia 1','Serbia 2','No','Yes'),
	array('Serbia 1','Trieste 1','No','Yes'),
	array('Serbia 2','Trieste 2','No','Yes'),
	array('Sevastopol 1','Sevastopol 2','Yes','Yes'),
	array('Sevastopol 1','Ukraine 1','No','Yes'),
	array('Sevastopol 2','Ukraine 2','No','Yes'),
	array('Silesia 1','Silesia 2','No','Yes'),
	array('Silesia 1','Warsaw 1','No','Yes'),
	array('Silesia 2','Warsaw 2','No','Yes'),
	array('Skagerrack 1','Skagerrack 2','Yes','No'),
	array('Skagerrack 1','Sweden 1','Yes','No'),
	array('Skagerrack 2','Sweden 2','Yes','No'),
	array('Smyrna 1','Smyrna 2','Yes','Yes'),
	array('Smyrna 1','Syria 1','Yes','Yes'),
	array('Smyrna 2','Syria 2','Yes','Yes'),
	array('Spain 1','Spain 2','No','Yes'),
	array('Spain 1 (North Coast)','Spain 2 (North Coast)','Yes','No'),
	array('Spain 1 (South Coast)','Spain 2 (South Coast)','Yes','No'),
	array('Spain 1 (South Coast)','Western Mediterranean 1','Yes','No'),
	array('Spain 2 (South Coast)','Western Mediterranean 2','Yes','No'),
	array('St. Petersburg 1','St. Petersburg 2','No','Yes'),
	array('St. Petersburg 1 (North Coast)','St. Petersburg 2 (North Coast)','Yes','No'),
	array('St. Petersburg 1 (South Coast)','St. Petersburg 2 (South Coast)','Yes','No'),
	array('Sweden 1','Sweden 2','Yes','Yes'),
	array('Syria 1','Syria 2','Yes','Yes'),
	array('Trieste 1','Trieste 2','Yes','Yes'),
	array('Trieste 1','Tyrolia 1','No','Yes'),
	array('Trieste 1','Venice 1','Yes','Yes'),
	array('Trieste 1','Vienna 1','No','Yes'),
	array('Trieste 2','Tyrolia 2','No','Yes'),
	array('Trieste 2','Venice 2','Yes','Yes'),
	array('Trieste 2','Vienna 2','No','Yes'),
	array('Tunis 1','Tunis 2','Yes','Yes'),
	array('Tunis 1','Tyrrhenian Sea 1','Yes','No'),
	array('Tunis 1','Western Mediterranean 1','Yes','No'),
	array('Tunis 2','Tyrrhenian Sea 2','Yes','No'),
	array('Tunis 2','Western Mediterranean 2','Yes','No'),
	array('Tuscany 1','Tuscany 2','Yes','Yes'),
	array('Tuscany 1','Tyrrhenian Sea 1','Yes','No'),
	array('Tuscany 1','Venice 1','No','Yes'),
	array('Tuscany 2','Tyrrhenian Sea 2','Yes','No'),
	array('Tuscany 2','Venice 2','No','Yes'),
	array('Tyrolia 1','Tyrolia 2','No','Yes'),
	array('Tyrolia 1','Venice 1','No','Yes'),
	array('Tyrolia 1','Vienna 1','No','Yes'),
	array('Tyrolia 2','Venice 2','No','Yes'),
	array('Tyrolia 2','Vienna 2','No','Yes'),
	array('Tyrrhenian Sea 1','Tyrrhenian Sea 2','Yes','No'),
	array('Tyrrhenian Sea 1','Western Mediterranean 1','Yes','No'),
	array('Tyrrhenian Sea 2','Western Mediterranean 2','Yes','No'),
	array('Ukraine 1','Ukraine 2','No','Yes'),
	array('Ukraine 1','Warsaw 1','No','Yes'),
	array('Ukraine 2','Warsaw 2','No','Yes'),
	array('Venice 1','Venice 2','Yes','Yes'),
	array('Vienna 1','Vienna 2','No','Yes'),
	array('Wales 1','Wales 2','Yes','Yes'),
	array('Wales 1','Yorkshire 1','No','Yes'),
	array('Wales 2','Yorkshire 2','No','Yes'),
	array('Warsaw 1','Warsaw 2','No','Yes'),
	array('Western Mediterranean 1','Western Mediterranean 2','Yes','No'),
	array('Yorkshire 1','Yorkshire 2','Yes','Yes')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
