<?php
// This is file installs the map data for the AberrationV variant
defined('IN_CODE') or die('This script can not be run by itself.');
require_once("variants/install.php");

InstallTerritory::$Territories=array();
$countries=$this->countries;
$territoryRawData=array(
	array('Clyde', 'Coast', 'No', 4, 334, 198, 166, 102),
	array('Edinburgh', 'Coast', 'Yes', 4, 348, 235, 179, 115),
	array('Alcuyd', 'Coast', 'Yes', 4, 325, 261, 163, 132),
	array('Yorkshire', 'Coast', 'No', 0, 368, 311, 183, 157),
	array('Cymru', 'Coast', 'No', 4, 295, 336, 142, 168),
	array('Cornwall', 'Coast', 'No', 0, 278, 367, 138, 183),
	array('Wessex', 'Coast', 'Yes', 0, 370, 370, 186, 184),
	array('Ulster', 'Coast', 'No', 4, 278, 257, 130, 130),
	array('Dublin', 'Coast', 'Yes', 4, 242, 290, 122, 145),
	array('Norway', 'Coast', 'Yes', 0, 526, 226, 259, 113),
	array('Sweden', 'Coast', 'Yes', 0, 606, 301, 300, 154),
	array('Norromark', 'Coast', 'No', 0, 667, 148, 333, 76),
	array('Lapland', 'Coast', 'No', 0, 636, 80, 327, 32),
	array('Finland', 'Coast', 'No', 0, 704, 219, 353, 110),
	array('Karelia', 'Coast', 'No', 0, 809, 96, 398, 51),
	array('Siberia', 'Coast', 'No', 0, 1100, 72, 538, 39),
	array('Volga', 'Land', 'No', 0, 1077, 388, 530, 195),
	array('Kazakhstan', 'Land', 'No', 0, 1334, 456, 655, 228),
	array('Turkestan', 'Land', 'Yes', 0, 1462, 619, 723, 304),
	array('Iran', 'Coast', 'Yes', 0, 1351, 855, 670, 423),
	array('Circassia', 'Coast', 'No', 0, 1126, 505, 534, 279),
	array('Azerbaijan', 'Land', 'No', 0, 1227, 608, 610, 301),
	array('Georgia', 'Coast', 'Yes', 0, 1091, 594, 552, 296),
	array('Novgorod', 'Coast', 'Yes', 0, 795, 268, 397, 136),
	array('Muscovy', 'Land', 'Yes', 0, 823, 384, 410, 192),
	array('Kuban', 'Coast', 'No', 0, 1024, 540, 518, 266),
	array('Armenia', 'Coast', 'Yes', 0, 1079, 617, 540, 312),
	array('Mesopotamia', 'Coast', 'No', 0, 1187, 844, 600, 427),
	array('Arabia', 'Coast', 'No', 0, 1277, 1076, 634, 539),
	array('Anatolia', 'Coast', 'Yes', 0, 965, 625, 482, 311),
	array('Cilicia', 'Coast', 'No', 0, 1011, 718, 504, 357),
	array('Syria', 'Coast', 'No', 0, 1040, 754, 518, 373),
	array('Riga', 'Coast', 'Yes', 6, 736, 283, 354, 160),
	array('Livonia', 'Land', 'No', 6, 742, 382, 370, 188),
	array('Masuria', 'Coast', 'No', 6, 711, 350, 355, 176),
	array('Gdansk', 'Coast', 'Yes', 6, 638, 378, 322, 188),
	array('Warsaw', 'Land', 'Yes', 6, 723, 415, 362, 207),
	array('Silesia', 'Land', 'No', 6, 624, 442, 312, 220),
	array('Galicia', 'Land', 'No', 6, 707, 461, 354, 228),
	array('Podolia', 'Land', 'No', 9, 773, 451, 386, 224),
	array('Kiev', 'Land', 'Yes', 9, 908, 426, 454, 212),
	array('Don', 'Land', 'No', 9, 973, 454, 486, 225),
	array('Taurida', 'Coast', 'No', 9, 943, 521, 476, 258),
	array('Odessa', 'Coast', 'Yes', 9, 867, 530, 438, 266),
	array('Yalta', 'Coast', 'Yes', 9, 955, 545, 476, 271),
	array('Rumania', 'Coast', 'Yes', 0, 848, 576, 424, 291),
	array('Bulgaria', 'Coast', 'Yes', 0, 839, 612, 421, 309),
	array('Athens', 'Coast', 'Yes', 2, 732, 750, 361, 365),
	array('Thrace', 'Coast', 'No', 2, 795, 654, 394, 330),
	array('Constantinople', 'Coast', 'Yes', 2, 869, 669, 428, 336),
	array('Aitolia', 'Coast', 'No', 2, 832, 704, 418, 353),
	array('Smyrna', 'Coast', 'Yes', 2, 894, 749, 443, 376),
	array('Pisidia', 'Coast', 'No', 2, 952, 735, 474, 365),
	array('Damascus', 'Coast', 'Yes', 5, 1034, 804, 517, 404),
	array('Jerusalem', 'Coast', 'Yes', 5, 1012, 861, 503, 430),
	array('Sinai', 'Coast', 'No', 5, 976, 878, 500, 461),
	array('Cairo', 'Coast', 'Yes', 5, 957, 893, 478, 459),
	array('Egypt', 'Coast', 'No', 5, 1019, 1043, 510, 516),
	array('Alamein', 'Coast', 'No', 5, 853, 892, 426, 451),
	array('Cyrenacia', 'Coast', 'Yes', 0, 715, 889, 352, 457),
	array('Fezzan', 'Land', 'No', 0, 466, 987, 237, 488),
	array('Sahara', 'Land', 'No', 0, 262, 925, 143, 469),
	array('Tripolitania', 'Coast', 'No', 0, 499, 873, 261, 431),
	array('Morocco', 'Coast', 'Yes', 0, 142, 757, 70, 371),
	array('Algeria', 'Coast', 'No', 0, 312, 768, 154, 380),
	array('Tunisia', 'Coast', 'Yes', 0, 455, 763, 222, 384),
	array('Lemburg', 'Land', 'No', 3, 736, 482, 368, 240),
	array('Denmark', 'Coast', 'Yes', 0, 537, 293, 263, 161),
	array('Holstein', 'Coast', 'No', 0, 525, 354, 262, 176),
	array('Transylvania', 'Land', 'No', 3, 728, 537, 365, 268),
	array('Albania', 'Coast', 'No', 0, 686, 695, 342, 344),
	array('Macedonia', 'Land', 'No', 0, 718, 669, 358, 336),
	array('Serbia', 'Land', 'No', 0, 708, 629, 349, 312),
	array('Zara', 'Coast', 'Yes', 3, 636, 617, 324, 310),
	array('Croatia', 'Coast', 'No', 3, 584, 566, 289, 279),
	array('Szeged', 'Land', 'Yes', 3, 702, 546, 349, 272),
	array('Budapest', 'Land', 'Yes', 3, 690, 517, 341, 255),
	array('Pomerania', 'Coast', 'No', 0, 582, 378, 286, 185),
	array('Saxony', 'Land', 'Yes', 0, 566, 417, 283, 210),
	array('Bohemia', 'Land', 'Yes', 0, 579, 470, 287, 233),
	array('Austria', 'Land', 'Yes', 0, 643, 481, 323, 239),
	array('Hessia', 'Coast', 'Yes', 0, 498, 366, 246, 184),
	array('Bavaria', 'Land', 'Yes', 0, 514, 453, 257, 226),
	array('Tyrol', 'Land', 'No', 0, 545, 522, 271, 259),
	array('Venice', 'Coast', 'Yes', 0, 528, 589, 263, 292),
	array('Schwyz', 'Land', 'No', 0, 461, 502, 230, 258),
	array('Piedmont', 'Coast', 'Yes', 0, 458, 575, 226, 284),
	array('Sardinia', 'Coast', 'No', 0, 440, 670, 219, 333),
	array('Tuscany', 'Coast', 'No', 7, 505, 612, 250, 309),
	array('Umbria', 'Coast', 'No', 7, 555, 641, 278, 322),
	array('Apulia', 'Coast', 'No', 7, 630, 698, 312, 348),
	array('Naples', 'Coast', 'Yes', 7, 578, 744, 293, 356),
	array('Rome', 'Coast', 'Yes', 7, 528, 642, 266, 325),
	array('Palermo', 'Coast', 'Yes', 7, 525, 755, 266, 377),
	array('Portugal', 'Coast', 'Yes', 0, 110, 647, 52, 321),
	array('Brittany', 'Coast', 'Yes', 0, 274, 436, 134, 216),
	array('Gascony', 'Coast', 'No', 0, 273, 572, 136, 281),
	array('Picardy', 'Coast', 'No', 0, 366, 414, 182, 206),
	array('France', 'Land', 'No', 0, 352, 485, 174, 240),
	array('Brussels', 'Coast', 'Yes', 1, 396, 398, 195, 200),
	array('Hague', 'Coast', 'Yes', 1, 457, 383, 230, 189),
	array('Ruhr', 'Land', 'No', 1, 460, 420, 231, 208),
	array('Swabia', 'Land', 'No', 1, 486, 460, 243, 228),
	array('Lorraine', 'Land', 'No', 1, 428, 449, 213, 225),
	array('Dijon', 'Land', 'Yes', 1, 388, 505, 191, 250),
	array('Languedoc', 'Coast', 'Yes', 0, 385, 582, 188, 290),
	array('Gibraltir', 'Coast', 'No', 8, 152, 690, 76, 348),
	array('Valencia', 'Coast', 'Yes', 8, 187, 685, 115, 343),
	array('Catalonia', 'Coast', 'No', 8, 286, 614, 145, 309),
	array('Estremadura', 'Land', 'No', 8, 154, 627, 78, 312),
	array('Toledo', 'Land', 'Yes', 8, 192, 649, 102, 313),
	array('Santiago', 'Coast', 'Yes', 8, 175, 570, 90, 278),
	array('Barents Sea', 'Sea', 'No', 0, 799, 29, 417, 27),
	array('Arctic Ocean', 'Sea', 'No', 0, 521, 27, 258, 16),
	array('North Atlantic Ocean', 'Sea', 'No', 0, 118, 250, 47, 120),
	array('Minch Sea', 'Sea', 'No', 0, 284, 236, 138, 116),
	array('Norwegian Sea', 'Sea', 'No', 0, 442, 133, 206, 68),
	array('North Sea', 'Sea', 'No', 0, 432, 270, 220, 132),
	array('Irish Sea', 'Sea', 'No', 0, 200, 379, 126, 171),
	array('Skagerrak', 'Sea', 'No', 0, 560, 284, 283, 146),
	array('Gulf of Bothnia', 'Sea', 'No', 0, 671, 219, 335, 109),
	array('Latvian Sea', 'Sea', 'No', 0, 668, 277, 327, 138),
	array('Baltic Sea', 'Sea', 'No', 0, 641, 355, 324, 175),
	array('Anglican Sea', 'Sea', 'No', 0, 414, 358, 202, 180),
	array('Heligoland Bight', 'Sea', 'No', 0, 488, 322, 242, 160),
	array('Bornholm Sea', 'Sea', 'No', 0, 610, 359, 306, 181),
	array('Indian Ocean', 'Sea', 'No', 0, 1448, 1129, 736, 568),
	array('Persian Gulf', 'Sea', 'No', 0, 1277, 904, 641, 449),
	array('Red Sea', 'Sea', 'No', 0, 1101, 1102, 517, 487),
	array('Delta Sea', 'Sea', 'No', 0, 956, 852, 486, 420),
	array('Libyan Sea', 'Sea', 'No', 0, 834, 829, 416, 414),
	array('Tobruk Sea', 'Sea', 'No', 0, 645, 835, 323, 418),
	array('Pylos Sea', 'Sea', 'No', 0, 734, 820, 362, 412),
	array('Carian Sea', 'Sea', 'No', 0, 928, 796, 431, 394),
	array('Eastern Mediterranean', 'Sea', 'No', 0, 1012, 787, 506, 390),
	array('Aegean Sea', 'Sea', 'No', 0, 787, 729, 394, 360),
	array('Malta Sea', 'Sea', 'No', 0, 584, 795, 286, 396),
	array('Ionian Sea', 'Sea', 'No', 0, 643, 761, 323, 382),
	array('Adriatic Sea', 'Sea', 'No', 0, 655, 674, 321, 337),
	array('Tyrrhenian Sea', 'Sea', 'No', 0, 479, 684, 250, 339),
	array('Utica Sea', 'Sea', 'No', 0, 383, 688, 186, 344),
	array('Western Mediterranean', 'Sea', 'No', 0, 261, 706, 129, 352),
	array('Palma Sea', 'Sea', 'No', 0, 279, 664, 154, 318),
	array('Gulf of Lyon', 'Sea', 'No', 0, 378, 639, 186, 321),
	array('Liguirian Sea', 'Sea', 'No', 0, 453, 606, 221, 306),
	array('Ifni Sea', 'Sea', 'No', 0, 16, 762, 6, 384),
	array('South Atlantic Ocean', 'Sea', 'No', 0, 43, 661, 22, 340),
	array('Bay of Biscay', 'Sea', 'No', 0, 233, 476, 114, 240),
	array('Mid Atlantic Ocean', 'Sea', 'No', 0, 145, 469, 36, 248),
	array('West Black Sea', 'Sea', 'No', 0, 932, 585, 456, 283),
	array('East Black Sea', 'Sea', 'No', 0, 1018, 576, 510, 286),
	array('English Channel', 'Sea', 'No', 0, 294, 414, 148, 205)
);

foreach($territoryRawData as $territoryRawRow)
{
	list($name, $type, $supply, $countryID, $x, $y, $sx, $sy)=$territoryRawRow;
	new InstallTerritory($name, $type, $supply, $countryID, $x, $y, $sx, $sy);
}
unset($territoryRawData);

$bordersRawData=array(
	array('Clyde','Edinburgh','Yes','Yes'),
	array('Clyde','Alcuyd','Yes','Yes'),
	array('Clyde','Minch Sea','Yes','No'),
	array('Clyde','Norwegian Sea','Yes','No'),
	array('Edinburgh','Alcuyd','No','Yes'),
	array('Edinburgh','Yorkshire','Yes','Yes'),
	array('Edinburgh','Norwegian Sea','Yes','No'),
	array('Edinburgh','North Sea','Yes','No'),
	array('Alcuyd','Yorkshire','No','Yes'),
	array('Alcuyd','Cymru','Yes','Yes'),
	array('Alcuyd','Minch Sea','Yes','No'),
	array('Alcuyd','Irish Sea','Yes','No'),
	array('Yorkshire','Cymru','No','Yes'),
	array('Yorkshire','Wessex','Yes','Yes'),
	array('Yorkshire','North Sea','Yes','No'),
	array('Yorkshire','Anglican Sea','Yes','No'),
	array('Cymru','Cornwall','Yes','Yes'),
	array('Cymru','Wessex','No','Yes'),
	array('Cymru','Irish Sea','Yes','No'),
	array('Cornwall','Wessex','Yes','Yes'),
	array('Cornwall','Irish Sea','Yes','No'),
	array('Cornwall','English Channel','Yes','No'),
	array('Wessex','Anglican Sea','Yes','No'),
	array('Wessex','English Channel','Yes','No'),
	array('Ulster','Dublin','Yes','Yes'),
	array('Ulster','North Atlantic Ocean','Yes','No'),
	array('Ulster','Minch Sea','Yes','No'),
	array('Ulster','Irish Sea','Yes','No'),
	array('Dublin','North Atlantic Ocean','Yes','No'),
	array('Dublin','Irish Sea','Yes','No'),
	array('Norway','Sweden','Yes','Yes'),
	array('Norway','Norromark','No','Yes'),
	array('Norway','Lapland','Yes','Yes'),
	array('Norway','Norwegian Sea','Yes','No'),
	array('Norway','North Sea','Yes','No'),
	array('Norway','Skagerrak','Yes','No'),
	array('Sweden','Norromark','Yes','Yes'),
	array('Sweden','Denmark','Yes','Yes'),
	array('Sweden','Skagerrak','Yes','No'),
	array('Sweden','Gulf of Bothnia','Yes','No'),
	array('Sweden','Latvian Sea','Yes','No'),
	array('Sweden','Baltic Sea','Yes','No'),
	array('Sweden','Bornholm Sea','Yes','No'),
	array('Norromark','Lapland','No','Yes'),
	array('Norromark','Finland','Yes','Yes'),
	array('Norromark','Gulf of Bothnia','Yes','No'),
	array('Lapland','Finland','No','Yes'),
	array('Lapland','Karelia','Yes','Yes'),
	array('Lapland','Barents Sea','Yes','No'),
	array('Lapland','Norwegian Sea','Yes','No'),
	array('Finland','Karelia','No','Yes'),
	array('Finland','Novgorod','Yes','Yes'),
	array('Finland','Gulf of Bothnia','Yes','No'),
	array('Finland','Latvian Sea','Yes','No'),
	array('Karelia','Siberia','Yes','Yes'),
	array('Karelia','Volga','No','Yes'),
	array('Karelia','Novgorod','No','Yes'),
	array('Karelia','Muscovy','No','Yes'),
	array('Karelia','Barents Sea','Yes','No'),
	array('Siberia','Volga','No','Yes'),
	array('Siberia','Kazakhstan','No','Yes'),
	array('Siberia','Barents Sea','Yes','No'),
	array('Volga','Kazakhstan','No','Yes'),
	array('Volga','Circassia','No','Yes'),
	array('Volga','Muscovy','No','Yes'),
	array('Volga','Don','No','Yes'),
	array('Kazakhstan','Turkestan','No','Yes'),
	array('Turkestan','Iran','No','Yes'),
	array('Iran','Azerbaijan','No','Yes'),
	array('Iran','Georgia','No','Yes'),
	array('Iran','Armenia','No','Yes'),
	array('Iran','Mesopotamia','Yes','Yes'),
	array('Iran','Indian Ocean','Yes','No'),
	array('Iran','Persian Gulf','Yes','No'),
	array('Circassia','Azerbaijan','No','Yes'),
	array('Circassia','Georgia','Yes','Yes'),
	array('Circassia','Kuban','Yes','Yes'),
	array('Circassia','Don','No','Yes'),
	array('Azerbaijan','Georgia','No','Yes'),
	array('Georgia','Armenia','Yes','Yes'),
	array('Georgia','East Black Sea','Yes','No'),
	array('Novgorod','Muscovy','No','Yes'),
	array('Novgorod','Riga','Yes','Yes'),
	array('Novgorod','Livonia','No','Yes'),
	array('Novgorod','Latvian Sea','Yes','No'),
	array('Muscovy','Livonia','No','Yes'),
	array('Muscovy','Warsaw','No','Yes'),
	array('Muscovy','Podolia','No','Yes'),
	array('Muscovy','Kiev','No','Yes'),
	array('Muscovy','Don','No','Yes'),
	array('Kuban','Don','No','Yes'),
	array('Kuban','Taurida','Yes','Yes'),
	array('Kuban','East Black Sea','Yes','No'),
	array('Armenia','Mesopotamia','No','Yes'),
	array('Armenia','Anatolia','Yes','Yes'),
	array('Armenia','Cilicia','No','Yes'),
	array('Armenia','Syria','No','Yes'),
	array('Armenia','East Black Sea','Yes','No'),
	array('Mesopotamia','Arabia','Yes','Yes'),
	array('Mesopotamia','Syria','No','Yes'),
	array('Mesopotamia','Persian Gulf','Yes','No'),
	array('Arabia','Syria','No','Yes'),
	array('Arabia','Damascus','No','Yes'),
	array('Arabia','Jerusalem','No','Yes'),
	array('Arabia','Sinai','Yes','Yes'),
	array('Arabia','Indian Ocean','Yes','No'),
	array('Arabia','Persian Gulf','Yes','No'),
	array('Arabia','Red Sea','Yes','No'),
	array('Anatolia','Cilicia','No','Yes'),
	array('Anatolia','Constantinople','Yes','Yes'),
	array('Anatolia','Pisidia','No','Yes'),
	array('Anatolia','West Black Sea','Yes','No'),
	array('Anatolia','East Black Sea','Yes','No'),
	array('Cilicia','Syria','Yes','Yes'),
	array('Cilicia','Pisidia','Yes','Yes'),
	array('Cilicia','Eastern Mediterranean','Yes','No'),
	array('Syria','Damascus','Yes','Yes'),
	array('Syria','Eastern Mediterranean','Yes','No'),
	array('Riga','Livonia','No','Yes'),
	array('Riga','Masuria','Yes','Yes'),
	array('Riga','Latvian Sea','Yes','No'),
	array('Riga','Baltic Sea','Yes','No'),
	array('Livonia','Masuria','No','Yes'),
	array('Livonia','Warsaw','No','Yes'),
	array('Masuria','Gdansk','Yes','Yes'),
	array('Masuria','Warsaw','No','Yes'),
	array('Masuria','Baltic Sea','Yes','No'),
	array('Gdansk','Warsaw','No','Yes'),
	array('Gdansk','Silesia','No','Yes'),
	array('Gdansk','Pomerania','Yes','Yes'),
	array('Gdansk','Saxony','No','Yes'),
	array('Gdansk','Baltic Sea','Yes','No'),
	array('Gdansk','Bornholm Sea','Yes','No'),
	array('Warsaw','Silesia','No','Yes'),
	array('Warsaw','Galicia','No','Yes'),
	array('Warsaw','Podolia','No','Yes'),
	array('Silesia','Galicia','No','Yes'),
	array('Silesia','Saxony','No','Yes'),
	array('Silesia','Bohemia','No','Yes'),
	array('Galicia','Podolia','No','Yes'),
	array('Galicia','Lemburg','No','Yes'),
	array('Galicia','Budapest','No','Yes'),
	array('Galicia','Bohemia','No','Yes'),
	array('Galicia','Austria','No','Yes'),
	array('Podolia','Kiev','No','Yes'),
	array('Podolia','Odessa','No','Yes'),
	array('Podolia','Rumania','No','Yes'),
	array('Podolia','Lemburg','No','Yes'),
	array('Kiev','Don','No','Yes'),
	array('Kiev','Odessa','No','Yes'),
	array('Don','Taurida','No','Yes'),
	array('Don','Odessa','No','Yes'),
	array('Taurida','Odessa','Yes','Yes'),
	array('Taurida','Yalta','Yes','Yes'),
	array('Taurida','West Black Sea','Yes','No'),
	array('Taurida','East Black Sea','Yes','No'),
	array('Odessa','Rumania','Yes','Yes'),
	array('Odessa','West Black Sea','Yes','No'),
	array('Yalta','West Black Sea','Yes','No'),
	array('Yalta','East Black Sea','Yes','No'),
	array('Rumania','Bulgaria','Yes','Yes'),
	array('Rumania','Lemburg','No','Yes'),
	array('Rumania','Transylvania','No','Yes'),
	array('Rumania','Serbia','No','Yes'),
	array('Rumania','West Black Sea','Yes','No'),
	array('Bulgaria','Athens','No','Yes'),
	array('Bulgaria','Thrace','No','Yes'),
	array('Bulgaria','Constantinople','Yes','Yes'),
	array('Bulgaria','Macedonia','No','Yes'),
	array('Bulgaria','Serbia','No','Yes'),
	array('Bulgaria','West Black Sea','Yes','No'),
	array('Athens','Thrace','Yes','Yes'),
	array('Athens','Albania','Yes','Yes'),
	array('Athens','Macedonia','No','Yes'),
	array('Athens','Pylos Sea','Yes','No'),
	array('Athens','Aegean Sea','Yes','No'),
	array('Athens','Ionian Sea','Yes','No'),
	array('Thrace','Constantinople','Yes','Yes'),
	array('Thrace','Aegean Sea','Yes','No'),
	array('Constantinople','Aitolia','Yes','Yes'),
	array('Constantinople','Smyrna','No','Yes'),
	array('Constantinople','Pisidia','No','Yes'),
	array('Constantinople','Aegean Sea','Yes','No'),
	array('Constantinople','West Black Sea','Yes','No'),
	array('Aitolia','Smyrna','Yes','Yes'),
	array('Aitolia','Aegean Sea','Yes','No'),
	array('Smyrna','Pisidia','Yes','Yes'),
	array('Smyrna','Carian Sea','Yes','No'),
	array('Smyrna','Aegean Sea','Yes','No'),
	array('Pisidia','Carian Sea','Yes','No'),
	array('Pisidia','Eastern Mediterranean','Yes','No'),
	array('Damascus','Jerusalem','Yes','Yes'),
	array('Damascus','Delta Sea','Yes','No'),
	array('Damascus','Eastern Mediterranean','Yes','No'),
	array('Jerusalem','Sinai','Yes','Yes'),
	array('Jerusalem','Delta Sea','Yes','No'),
	array('Sinai','Cairo','Yes','Yes'),
	array('Sinai','Red Sea','Yes','No'),
	array('Sinai','Delta Sea','Yes','No'),
	array('Cairo','Egypt','Yes','Yes'),
	array('Cairo','Alamein','Yes','Yes'),
	array('Cairo','Red Sea','Yes','No'),
	array('Cairo','Delta Sea','Yes','No'),
	array('Cairo','Libyan Sea','Yes','No'),
	array('Egypt','Alamein','No','Yes'),
	array('Egypt','Cyrenacia','No','Yes'),
	array('Egypt','Red Sea','Yes','No'),
	array('Alamein','Cyrenacia','Yes','Yes'),
	array('Alamein','Libyan Sea','Yes','No'),
	array('Cyrenacia','Fezzan','No','Yes'),
	array('Cyrenacia','Tripolitania','Yes','Yes'),
	array('Cyrenacia','Libyan Sea','Yes','No'),
	array('Cyrenacia','Tobruk Sea','Yes','No'),
	array('Cyrenacia','Pylos Sea','Yes','No'),
	array('Fezzan','Sahara','No','Yes'),
	array('Fezzan','Tripolitania','No','Yes'),
	array('Sahara','Tripolitania','No','Yes'),
	array('Sahara','Morocco','No','Yes'),
	array('Sahara','Algeria','No','Yes'),
	array('Sahara','Tunisia','No','Yes'),
	array('Tripolitania','Tunisia','Yes','Yes'),
	array('Tripolitania','Tobruk Sea','Yes','No'),
	array('Tripolitania','Malta Sea','Yes','No'),
	array('Morocco','Algeria','Yes','Yes'),
	array('Morocco','Western Mediterranean','Yes','No'),
	array('Morocco','Ifni Sea','Yes','No'),
	array('Morocco','South Atlantic Ocean','Yes','No'),
	array('Algeria','Tunisia','Yes','Yes'),
	array('Algeria','Utica Sea','Yes','No'),
	array('Algeria','Western Mediterranean','Yes','No'),
	array('Tunisia','Malta Sea','Yes','No'),
	array('Tunisia','Tyrrhenian Sea','Yes','No'),
	array('Tunisia','Utica Sea','Yes','No'),
	array('Lemburg','Transylvania','No','Yes'),
	array('Lemburg','Budapest','No','Yes'),
	array('Denmark','Holstein','Yes','Yes'),
	array('Denmark','North Sea','Yes','No'),
	array('Denmark','Skagerrak','Yes','No'),
	array('Denmark','Heligoland Bight','Yes','No'),
	array('Denmark','Bornholm Sea','Yes','No'),
	array('Holstein','Pomerania','Yes','Yes'),
	array('Holstein','Hessia','Yes','Yes'),
	array('Holstein','Heligoland Bight','Yes','No'),
	array('Holstein','Bornholm Sea','Yes','No'),
	array('Transylvania','Serbia','No','Yes'),
	array('Transylvania','Szeged','No','Yes'),
	array('Transylvania','Budapest','No','Yes'),
	array('Albania','Macedonia','No','Yes'),
	array('Albania','Serbia','No','Yes'),
	array('Albania','Zara','Yes','Yes'),
	array('Albania','Ionian Sea','Yes','No'),
	array('Albania','Adriatic Sea','Yes','No'),
	array('Macedonia','Serbia','No','Yes'),
	array('Serbia','Zara','No','Yes'),
	array('Serbia','Croatia','No','Yes'),
	array('Serbia','Szeged','No','Yes'),
	array('Zara','Croatia','Yes','Yes'),
	array('Zara','Adriatic Sea','Yes','No'),
	array('Croatia','Szeged','No','Yes'),
	array('Croatia','Budapest','No','Yes'),
	array('Croatia','Austria','No','Yes'),
	array('Croatia','Tyrol','No','Yes'),
	array('Croatia','Venice','Yes','Yes'),
	array('Croatia','Adriatic Sea','Yes','No'),
	array('Szeged','Budapest','No','Yes'),
	array('Budapest','Austria','No','Yes'),
	array('Pomerania','Saxony','No','Yes'),
	array('Pomerania','Hessia','No','Yes'),
	array('Pomerania','Bornholm Sea','Yes','No'),
	array('Saxony','Bohemia','No','Yes'),
	array('Saxony','Hessia','No','Yes'),
	array('Saxony','Bavaria','No','Yes'),
	array('Bohemia','Austria','No','Yes'),
	array('Bohemia','Bavaria','No','Yes'),
	array('Bohemia','Tyrol','No','Yes'),
	array('Austria','Tyrol','No','Yes'),
	array('Hessia','Bavaria','No','Yes'),
	array('Hessia','Hague','Yes','Yes'),
	array('Hessia','Ruhr','No','Yes'),
	array('Hessia','Heligoland Bight','Yes','No'),
	array('Bavaria','Tyrol','No','Yes'),
	array('Bavaria','Ruhr','No','Yes'),
	array('Bavaria','Swabia','No','Yes'),
	array('Tyrol','Venice','No','Yes'),
	array('Tyrol','Schwyz','No','Yes'),
	array('Tyrol','Piedmont','No','Yes'),
	array('Tyrol','Swabia','No','Yes'),
	array('Venice','Piedmont','No','Yes'),
	array('Venice','Tuscany','No','Yes'),
	array('Venice','Umbria','Yes','Yes'),
	array('Venice','Adriatic Sea','Yes','No'),
	array('Schwyz','Piedmont','No','Yes'),
	array('Schwyz','Swabia','No','Yes'),
	array('Schwyz','Lorraine','No','Yes'),
	array('Schwyz','Dijon','No','Yes'),
	array('Schwyz','Languedoc','No','Yes'),
	array('Piedmont','Tuscany','Yes','Yes'),
	array('Piedmont','Languedoc','Yes','Yes'),
	array('Piedmont','Liguirian Sea','Yes','No'),
	array('Sardinia','Tyrrhenian Sea','Yes','No'),
	array('Sardinia','Utica Sea','Yes','No'),
	array('Sardinia','Gulf of Lyon','Yes','No'),
	array('Tuscany','Umbria','No','Yes'),
	array('Tuscany','Rome','Yes','Yes'),
	array('Tuscany','Liguirian Sea','Yes','No'),
	array('Umbria','Apulia','Yes','Yes'),
	array('Umbria','Rome','No','Yes'),
	array('Umbria','Adriatic Sea','Yes','No'),
	array('Apulia','Naples','Yes','Yes'),
	array('Apulia','Rome','No','Yes'),
	array('Apulia','Malta Sea','Yes','No'),
	array('Apulia','Ionian Sea','Yes','No'),
	array('Apulia','Adriatic Sea','Yes','No'),
	array('Naples','Rome','Yes','Yes'),
	array('Naples','Malta Sea','Yes','No'),
	array('Naples','Tyrrhenian Sea','Yes','No'),
	array('Rome','Tyrrhenian Sea','Yes','No'),
	array('Rome','Liguirian Sea','Yes','No'),
	array('Palermo','Malta Sea','Yes','No'),
	array('Palermo','Tyrrhenian Sea','Yes','No'),
	array('Portugal','Gibraltir','Yes','Yes'),
	array('Portugal','Estremadura','No','Yes'),
	array('Portugal','Santiago','Yes','Yes'),
	array('Portugal','South Atlantic Ocean','Yes','No'),
	array('Brittany','Gascony','Yes','Yes'),
	array('Brittany','Picardy','Yes','Yes'),
	array('Brittany','France','No','Yes'),
	array('Brittany','Bay of Biscay','Yes','No'),
	array('Brittany','Mid Atlantic Ocean','Yes','No'),
	array('Brittany','English Channel','Yes','No'),
	array('Gascony','France','No','Yes'),
	array('Gascony','Dijon','No','Yes'),
	array('Gascony','Languedoc','No','Yes'),
	array('Gascony','Catalonia','No','Yes'),
	array('Gascony','Santiago','Yes','Yes'),
	array('Gascony','Bay of Biscay','Yes','No'),
	array('Picardy','France','No','Yes'),
	array('Picardy','Brussels','Yes','Yes'),
	array('Picardy','Lorraine','No','Yes'),
	array('Picardy','English Channel','Yes','No'),
	array('France','Lorraine','No','Yes'),
	array('France','Dijon','No','Yes'),
	array('Brussels','Hague','Yes','Yes'),
	array('Brussels','Ruhr','No','Yes'),
	array('Brussels','Lorraine','No','Yes'),
	array('Brussels','Anglican Sea','Yes','No'),
	array('Brussels','English Channel','Yes','No'),
	array('Hague','Ruhr','No','Yes'),
	array('Hague','Anglican Sea','Yes','No'),
	array('Hague','Heligoland Bight','Yes','No'),
	array('Ruhr','Swabia','No','Yes'),
	array('Ruhr','Lorraine','No','Yes'),
	array('Swabia','Lorraine','No','Yes'),
	array('Lorraine','Dijon','No','Yes'),
	array('Dijon','Languedoc','No','Yes'),
	array('Languedoc','Catalonia','Yes','Yes'),
	array('Languedoc','Gulf of Lyon','Yes','No'),
	array('Languedoc','Liguirian Sea','Yes','No'),
	array('Gibraltir','Valencia','Yes','Yes'),
	array('Gibraltir','Estremadura','No','Yes'),
	array('Gibraltir','Western Mediterranean','Yes','No'),
	array('Gibraltir','South Atlantic Ocean','Yes','No'),
	array('Valencia','Catalonia','Yes','Yes'),
	array('Valencia','Estremadura','No','Yes'),
	array('Valencia','Western Mediterranean','Yes','No'),
	array('Valencia','Palma Sea','Yes','No'),
	array('Catalonia','Toledo','No','Yes'),
	array('Catalonia','Santiago','No','Yes'),
	array('Catalonia','Palma Sea','Yes','No'),
	array('Catalonia','Gulf of Lyon','Yes','No'),
	array('Estremadura','Toledo','No','Yes'),
	array('Estremadura','Santiago','No','Yes'),
	array('Toledo','Santiago','No','Yes'),
	array('Santiago','South Atlantic Ocean','Yes','No'),
	array('Santiago','Bay of Biscay','Yes','No'),
	array('Santiago','Mid Atlantic Ocean','Yes','No'),
	array('Barents Sea','Arctic Ocean','Yes','No'),
	array('Barents Sea','Norwegian Sea','Yes','No'),
	array('Arctic Ocean','North Atlantic Ocean','Yes','No'),
	array('Arctic Ocean','Norwegian Sea','Yes','No'),
	array('North Atlantic Ocean','Minch Sea','Yes','No'),
	array('North Atlantic Ocean','Norwegian Sea','Yes','No'),
	array('North Atlantic Ocean','Irish Sea','Yes','No'),
	array('North Atlantic Ocean','Mid Atlantic Ocean','Yes','No'),
	array('Minch Sea','Norwegian Sea','Yes','No'),
	array('Minch Sea','Irish Sea','Yes','No'),
	array('Norwegian Sea','North Sea','Yes','No'),
	array('North Sea','Skagerrak','Yes','No'),
	array('North Sea','Anglican Sea','Yes','No'),
	array('North Sea','Heligoland Bight','Yes','No'),
	array('Irish Sea','Mid Atlantic Ocean','Yes','No'),
	array('Irish Sea','English Channel','Yes','No'),
	array('Gulf of Bothnia','Latvian Sea','Yes','No'),
	array('Latvian Sea','Baltic Sea','Yes','No'),
	array('Baltic Sea','Bornholm Sea','Yes','No'),
	array('Anglican Sea','Heligoland Bight','Yes','No'),
	array('Anglican Sea','English Channel','Yes','No'),
	array('Indian Ocean','Persian Gulf','Yes','No'),
	array('Indian Ocean','Red Sea','Yes','No'),
	array('Indian Ocean','Ifni Sea','Yes','No'),
	array('Delta Sea','Libyan Sea','Yes','No'),
	array('Delta Sea','Carian Sea','Yes','No'),
	array('Delta Sea','Eastern Mediterranean','Yes','No'),
	array('Libyan Sea','Pylos Sea','Yes','No'),
	array('Libyan Sea','Carian Sea','Yes','No'),
	array('Libyan Sea','Aegean Sea','Yes','No'),
	array('Tobruk Sea','Pylos Sea','Yes','No'),
	array('Tobruk Sea','Malta Sea','Yes','No'),
	array('Pylos Sea','Aegean Sea','Yes','No'),
	array('Pylos Sea','Malta Sea','Yes','No'),
	array('Pylos Sea','Ionian Sea','Yes','No'),
	array('Carian Sea','Eastern Mediterranean','Yes','No'),
	array('Carian Sea','Aegean Sea','Yes','No'),
	array('Malta Sea','Ionian Sea','Yes','No'),
	array('Malta Sea','Tyrrhenian Sea','Yes','No'),
	array('Ionian Sea','Adriatic Sea','Yes','No'),
	array('Tyrrhenian Sea','Utica Sea','Yes','No'),
	array('Tyrrhenian Sea','Gulf of Lyon','Yes','No'),
	array('Tyrrhenian Sea','Liguirian Sea','Yes','No'),
	array('Utica Sea','Western Mediterranean','Yes','No'),
	array('Utica Sea','Palma Sea','Yes','No'),
	array('Utica Sea','Gulf of Lyon','Yes','No'),
	array('Western Mediterranean','Palma Sea','Yes','No'),
	array('Western Mediterranean','South Atlantic Ocean','Yes','No'),
	array('Palma Sea','Gulf of Lyon','Yes','No'),
	array('Gulf of Lyon','Liguirian Sea','Yes','No'),
	array('Ifni Sea','South Atlantic Ocean','Yes','No'),
	array('South Atlantic Ocean','Mid Atlantic Ocean','Yes','No'),
	array('Bay of Biscay','Mid Atlantic Ocean','Yes','No'),
	array('Mid Atlantic Ocean','English Channel','Yes','No'),
	array('West Black Sea','East Black Sea','Yes','No')
);

foreach($bordersRawData as $borderRawRow)
{
	list($from, $to, $fleets, $armies)=$borderRawRow;
	InstallTerritory::$Territories[$to]  ->addBorder(InstallTerritory::$Territories[$from],$fleets,$armies);
}
unset($bordersRawData);

InstallTerritory::runSQL($this->mapID);
InstallCache::terrJSON($this->territoriesJSONFile(),$this->mapID);
?>
